In [10]:
import os
import json
import pandas as pd
from unsloth import FastLanguageModel, is_bfloat16_supported
from unsloth.chat_templates import get_chat_template, train_on_responses_only
import torch

from vllm import LLM, SamplingParams
from vllm.sampling_params import GuidedDecodingParams

from pydantic import BaseModel, Field

from datasets import load_dataset, Dataset
from trl import SFTTrainer, SFTConfig
from transformers import TrainingArguments, DataCollatorForSeq2Seq, TextStreamer
from fractions import Fraction
from music21 import stream, note, chord, instrument, tempo, meter, key, midi

In [ ]:
# df = pd.read_json("data/MidiCaps/train_parsed.json", lines=True)

In [ ]:
# df.head()

,midi,caption,data
0,17655598958db48a34cd882f81402568,A short electronic ambient song featuring a pi...,"{""metadata"": {""bpm"": 170, ""time_signature"": ""4..."
1,1f94f64f72af98fd92f206293b281f6f,A classical piece that could be part of a film...,"{""metadata"": {""bpm"": 74, ""time_signature"": ""4/..."
2,112139e8b17be9cae1bd14df56e52f14,A short fragment of energetic electronic and c...,"{""metadata"": {""bpm"": 136, ""time_signature"": ""4..."
3,1a20c7ecf60469366d1121ea48fd3f6e,A short classical piece with electronic elemen...,"{""metadata"": {""bpm"": 108, ""time_signature"": ""4..."
4,1bdbd7f3ac595612d926d46206fff0c0,A very fast and short electronic piano piece i...,"{""metadata"": {""bpm"": 166, ""time_signature"": ""4..."

In [4]:
df.shape

(21907, 3)

In [2]:
max_seq_length = 4096 # Choose any! We auto support RoPE Scaling internally!
dtype = None # None for auto detection. Float16 for Tesla T4, V100, Bfloat16 for Ampere+
load_in_4bit = True # Use 4bit quantization to reduce memory usage. Can be False.

# 4bit pre quantized models we support for 4x faster downloading + no OOMs.
fourbit_models = [
    "unsloth/Meta-Llama-3.1-8B-bnb-4bit",      # Llama-3.1 2x faster
    "unsloth/Meta-Llama-3.1-70B-bnb-4bit",
    "unsloth/Mistral-Small-Instruct-2409",     # Mistral 22b 2x faster!
    "unsloth/mistral-7b-instruct-v0.3-bnb-4bit",
    "unsloth/Phi-3.5-mini-instruct",           # Phi-3.5 2x faster!
    "unsloth/Phi-3-medium-4k-instruct",
    "unsloth/gemma-2-27b-bnb-4bit",            # Gemma 2x faster!

    "unsloth/Llama-3.2-1B-bnb-4bit",           # NEW! Llama 3.2 models
    "unsloth/Llama-3.2-1B-Instruct-bnb-4bit",
    "unsloth/Llama-3.2-3B-Instruct-bnb-4bit",
] # More models at https://huggingface.co/unsloth

qwen_models = [
    "unsloth/Qwen2.5-Coder-32B-Instruct",      # Qwen 2.5 Coder 2x faster
    "unsloth/Qwen2.5-Coder-7B",
    "unsloth/Qwen2.5-14B-Instruct",            # 14B fits in a 16GB card
    "unsloth/Qwen2.5-7B",
    "unsloth/Qwen2.5-72B-Instruct",            # 72B fits in a 48GB card
] # More models at https://huggingface.co/unsloth

In [3]:
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "unsloth/Qwen3-14B",
    max_seq_length = max_seq_length,
    dtype = dtype,
    load_in_4bit = load_in_4bit,
    full_finetuning = False
)

==((====))==  Unsloth 2025.6.2: Fast Qwen3 patching. Transformers: 4.52.4. vLLM: 0.9.1.
   \\   /|    NVIDIA GeForce RTX 4090. Num GPUs = 1. Max memory: 23.505 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.7.0+cu126. CUDA: 8.9. CUDA Toolkit: 12.6. Triton: 3.3.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.30. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

In [4]:
model = FastLanguageModel.get_peft_model(
    model,
    r = 32,           # Choose any number > 0! Suggested 8, 16, 32, 64, 128
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj",
                      "gate_proj", "up_proj", "down_proj",],
    lora_alpha = 32,  # Best to choose alpha = rank or rank*2
    lora_dropout = 0, # Supports any, but = 0 is optimized
    bias = "none",    # Supports any, but = "none" is optimized
    # [NEW] "unsloth" uses 30% less VRAM, fits 2x larger batch sizes!
    use_gradient_checkpointing = "unsloth", # True or "unsloth" for very long context
    random_state = 3407,
    use_rslora = False,   # We support rank stabilized LoRA
    loftq_config = None,  # And LoftQ
)

Unsloth 2025.6.2 patched 40 layers with 40 QKV layers, 40 O layers and 40 MLP layers.

In [ ]:
# tokenizer = get_chat_template(
#     tokenizer,
#     chat_template = "qwen3",
# )

In [5]:
dataset = load_dataset('json', data_files='data/MidiCaps/train_parsed.json', split="train")

Generating train split: 0 examples [00:00, ? examples/s]

In [12]:
class MusicSchema(BaseModel):
    metadata: dict = Field(
        default_factory=lambda: {
            "tempo": int,
            "time_signature": "string",
            "key_signature": "string"
        }
    )
    chords: list = Field(
        default_factory=list,
    )
    tracks: list = Field(
        default_factory=list,
    )

def formatting_prompts(sample):
    prompt = "You are an assistant for music composer. Please generate a structured music by provided information: \n"
    prompt += sample['caption'] + "\n"
    prompt += "Generate the music output in JSON format. \n"
    # prompt += "```json \n"
    # prompt += "\n"

    question = {"content": prompt, "role": "user"}
    answer = {"content": sample['data'], "role": "assistant"}
    conv = [question, answer]
    prompt = tokenizer.apply_chat_template(conv, tokenize=False, add_generation_prompt=False)
   
    return {'prompt': prompt}

In [13]:
dataset[6]

{'midi': '181f95e8a6bd0838bca39f83e6678cb0',
 'caption': 'A classical piece, potentially used as a soundtrack, featuring a solo piano. The composition is set in G major with a 2/4 time signature and a moderate tempo of 92 beats per minute. Throughout the song, the chords Dm and G are repeated frequently, contributing to the dark, melodic, and emotional atmosphere, while also evoking a sense of relaxation and a cinematic quality.',

In [10]:
test = [{'content': 'Who is Binu?', 'role': 'user'}, {'content': 'She is a toddler.', 'role': 'assistant'}]
tokenizer.apply_chat_template(test, tokenize=False, add_generation_prompt=False)

'<|im_start|>user\nWho is Binu?<|im_end|>\n<|im_start|>assistant\n<think>\n\n</think>\n\nShe is a toddler.<|im_end|>\n'

In [14]:

train_set = dataset.map(formatting_prompts, remove_columns=dataset.column_names)

Map:   0%|          | 0/13904 [00:00<?, ? examples/s]

In [15]:
train_set[0]

{'prompt': '<|im_start|>user\nYou are an assistant for music composer. Please generate a structured music by provided information: \nA short electronic ambient song featuring a piano, set in E major with a 4/4 time signature and a Presto tempo. The composition evokes a cinematic, energetic, and melodic atmosphere with hints of epic and dark undertones. The chord progression of B, Emaj7, C#m7, B7, and A adds to its captivating ambiance.\nGenerate the music output in JSON format. \n<|im_end|>\n<|im_start|>assistant\n<think>\n\n</think>\n\n{"metadata": {"tempo": 170, "time_signature": "4/4", "key_signature": "E major"}, "chords": ["B", "Emaj7", "C#m7", "B7", "A"], "tracks": [{"name": "Piano", "instrument": "Pno", "measures": [{"measure_number": 1, "notes": [{"type": "chord", "name": "B(other)", "pitches": ["B4", "F#5", "B5", "B2", "B3"], "function": "dominant", "roman": "v5", "scale_degrees": [5, 2, 5, 5, 5], "onset": "0/1", "duration": "1/2", "velocity": 68}, {"type": "chord", "name": "B(other)", "pitches": ["B4", "F#5", "B5", "B2", "B3"], "function": "dominant", "roman": "v5", "scale_degrees": [5, 2, 5, 5, 5], "onset": "1/2", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "B(other)", "pitches": ["B4", "F#5", "B5", "B2", "B3"], "function": "dominant", "roman": "v5", "scale_degrees": [5, 2, 5, 5, 5], "onset": "3/2", "duration": "1/2", "velocity": 78}, {"type": "chord", "name": "E(other)", "pitches": ["B4", "E5", "B2", "B3"], "function": "tonic", "roman": "i4", "scale_degrees": [5, 1, 5, 5], "onset": "2/1", "duration": "1/1", "velocity": 68}, {"type": "chord", "name": "B(other)", "pitches": ["B4", "F#5", "B2", "B3"], "function": "dominant", "roman": "v5", "scale_degrees": [5, 2, 5, 5], "onset": "3/1", "duration": "1/1", "velocity": 80}]}, {"measure_number": 2, "notes": [{"type": "chord", "name": "E", "pitches": ["E5", "G#5"], "function": "tonic", "roman": "I", "scale_degrees": [1, 3], "onset": "0/1", "duration": "2/1", "velocity": 80}, {"type": "chord", "name": "E", "pitches": ["E5", "G#5"], "function": "tonic", "roman": "I", "scale_degrees": [1, 3], "onset": "2/1", "duration": "1/1", "velocity": 77}, {"type": "chord", "name": "E(other)", "pitches": ["E5", "G#5", "E-2"], "function": "tonic", "roman": "Ib83", "scale_degrees": [1, 3, 1], "onset": "3/1", "duration": "1/2", "velocity": 74}, {"type": "chord", "name": "E(other)", "pitches": ["E5", "B5", "E-3"], "function": "tonic", "roman": "ib85", "scale_degrees": [1, 5, 1], "onset": "7/2", "duration": "1/2", "velocity": 83}, {"type": "note", "name": "E", "pitch": "E2", "scale_degree": 1, "onset": "0/1", "duration": "1/2", "velocity": 68}, {"type": "note", "name": "E", "pitch": "E3", "scale_degree": 1, "onset": "1/2", "duration": "1/2", "velocity": 82}, {"type": "note", "name": "E", "pitch": "E2", "scale_degree": 1, "onset": "1/1", "duration": "1/2", "velocity": 69}, {"type": "note", "name": "E", "pitch": "E3", "scale_degree": 1, "onset": "3/2", "duration": "1/2", "velocity": 84}, {"type": "note", "name": "E-", "pitch": "E-2", "scale_degree": 0, "onset": "2/1", "duration": "1/2", "velocity": 72}, {"type": "note", "name": "E-", "pitch": "E-3", "scale_degree": 0, "onset": "5/2", "duration": "1/2", "velocity": 84}, {"type": "rest", "name": "Quarter Rest", "onset": "3/1", "duration": "1/1"}]}, {"measure_number": 3, "notes": [{"type": "note", "name": "C#", "pitch": "C#2", "scale_degree": 6, "onset": "0/1", "duration": "1/2", "velocity": 69}, {"type": "chord", "name": "C#m", "pitches": ["E5", "G#5", "C#3"], "function": "dominant", "roman": "vi", "scale_degrees": [1, 3, 6], "onset": "1/2", "duration": "1/2", "velocity": 73}, {"type": "chord", "name": "C#m", "pitches": ["E5", "B5", "C#2"], "function": "dominant", "roman": "vi7", "scale_degrees": [1, 5, 6], "onset": "1/1", "duration": "1/2", "velocity": 78}, {"type": "chord", "name": "C#m", "pitches": ["E5", "C#6", "C#3"], "function": "dominant", "roman": "vi", "scale_degrees": [1, 6, 6], "onset": "3/2", "duration": "1/2", "velocity": 81}, {"type": "chord", "name": "E(other)", "pitches": ["E5", "B5"], "function": "tonic", "roman": "i5", "scale_degrees": [1, 5], "onset": "2/1", "duration": "1/1", "velocity": 73}, {"type": "chord", "name": "A(other)", "pitches": ["E-5", "A5", "B1"], "function": "subdominant", "roman": "ivo7b4", "scale_degrees": [1, 4, 5], "onset": "3/1", "duration": "1/2", "velocity": 72}, {"type": "chord", "name": "A(other)", "pitches": ["E-5", "A5", "B2"], "function": "subdominant", "roman": "ivo7b4", "scale_degrees": [1, 4, 5], "onset": "7/2", "duration": "1/2", "velocity": 81}, {"type": "rest", "name": "Half Rest", "onset": "0/1", "duration": "2/1"}, {"type": "note", "name": "B", "pitch": "B1", "scale_degree": 5, "onset": "2/1", "duration": "1/2", "velocity": 68}, {"type": "note", "name": "B", "pitch": "B2", "scale_degree": 5, "onset": "5/2", "duration": "1/2", "velocity": 83}, {"type": "rest", "name": "Quarter Rest", "onset": "3/1", "duration": "1/1"}]}, {"measure_number": 4, "notes": [{"type": "chord", "name": "E", "pitches": ["E5", "G#5"], "function": "tonic", "roman": "I", "scale_degrees": [1, 3], "onset": "0/1", "duration": "1/1", "velocity": 73}, {"type": "chord", "name": "G#m", "pitches": ["G#5", "B5"], "function": "subdominant", "roman": "iii", "scale_degrees": [3, 5], "onset": "1/1", "duration": "1/1", "velocity": 82}, {"type": "chord", "name": "A(other)", "pitches": ["E5", "A5"], "function": "subdominant", "roman": "iv4", "scale_degrees": [1, 4], "onset": "2/1", "duration": "1/1", "velocity": 74}, {"type": "chord", "name": "E", "pitches": ["E5", "G#5"], "function": "tonic", "roman": "I", "scale_degrees": [1, 3], "onset": "3/1", "duration": "1/1", "velocity": 70}, {"type": "note", "name": "A", "pitch": "A1", "scale_degree": 4, "onset": "0/1", "duration": "1/2", "velocity": 66}, {"type": "note", "name": "A", "pitch": "A2", "scale_degree": 4, "onset": "1/2", "duration": "1/2", "velocity": 82}, {"type": "note", "name": "A", "pitch": "A1", "scale_degree": 4, "onset": "1/1", "duration": "1/2", "velocity": 64}, {"type": "note", "name": "A", "pitch": "A2", "scale_degree": 4, "onset": "3/2", "duration": "1/2", "velocity": 86}, {"type": "note", "name": "A", "pitch": "A1", "scale_degree": 4, "onset": "2/1", "duration": "1/2", "velocity": 69}, {"type": "note", "name": "A", "pitch": "A2", "scale_degree": 4, "onset": "5/2", "duration": "1/2", "velocity": 85}, {"type": "note", "name": "A", "pitch": "A1", "scale_degree": 4, "onset": "3/1", "duration": "1/2", "velocity": 66}, {"type": "note", "name": "A", "pitch": "A2", "scale_degree": 4, "onset": "7/2", "duration": "1/2", "velocity": 85}]}, {"measure_number": 5, "notes": [{"type": "chord", "name": "G#m", "pitches": ["B4", "G#5"], "function": "subdominant", "roman": "iii6", "scale_degrees": [5, 3], "onset": "0/1", "duration": "3/2", "velocity": 77}, {"type": "chord", "name": "B(other)", "pitches": ["F#5", "B2"], "function": "dominant", "roman": "v5", "scale_degrees": [2, 5], "onset": "3/2", "duration": "1/2", "velocity": 77}, {"type": "chord", "name": "E-(other)", "pitches": ["B4", "E-5", "F#5"], "function": "other", "roman": "bi+#54", "scale_degrees": [5, 1, 2], "onset": "2/1", "duration": "1/1", "velocity": 72}, {"type": "chord", "name": "E(other)", "pitches": ["B4", "E5", "B1"], "function": "tonic", "roman": "i4", "scale_degrees": [5, 1, 5], "onset": "3/1", "duration": "1/2", "velocity": 69}, {"type": "chord", "name": "B(other)", "pitches": ["B4", "F#5", "B2"], "function": "dominant", "roman": "v5", "scale_degrees": [5, 2, 5], "onset": "7/2", "duration": "1/2", "velocity": 85}, {"type": "note", "name": "B", "pitch": "B1", "scale_degree": 5, "onset": "0/1", "duration": "1/2", "velocity": 68}, {"type": "note", "name": "B", "pitch": "B2", "scale_degree": 5, "onset": "1/2", "duration": "1/2", "velocity": 83}, {"type": "note", "name": "B", "pitch": "B1", "scale_degree": 5, "onset": "1/1", "duration": "1/2", "velocity": 65}, {"type": "rest", "name": "Eighth Rest", "onset": "3/2", "duration": "1/2"}, {"type": "note", "name": "B", "pitch": "B1", "scale_degree": 5, "onset": "2/1", "duration": "1/2", "velocity": 68}, {"type": "note", "name": "B", "pitch": "B2", "scale_degree": 5, "onset": "5/2", "duration": "1/2", "velocity": 86}, {"type": "rest", "name": "Quarter Rest", "onset": "3/1", "duration": "1/1"}]}, {"measure_number": 6, "notes": [{"type": "chord", "name": "E", "pitches": ["E5", "G#5"], "function": "tonic", "roman": "I", "scale_degrees": [1, 3], "onset": "0/1", "duration": "2/1", "velocity": 85}, {"type": "chord", "name": "E", "pitches": ["E5", "G#5"], "function": "tonic", "roman": "I", "scale_degrees": [1, 3], "onset": "2/1", "duration": "1/1", "velocity": 80}, {"type": "chord", "name": "E(other)", "pitches": ["E5", "G#5", "E-2"], "function": "tonic", "roman": "Ib83", "scale_degrees": [1, 3, 1], "onset": "3/1", "duration": "1/2", "velocity": 70}, {"type": "chord", "name": "E(other)", "pitches": ["E5", "B5", "E-3"], "function": "tonic", "roman": "ib85", "scale_degrees": [1, 5, 1], "onset": "7/2", "duration": "1/2", "velocity": 85}, {"type": "note", "name": "E", "pitch": "E2", "scale_degree": 1, "onset": "0/1", "duration": "1/2", "velocity": 74}, {"type": "note", "name": "E", "pitch": "E3", "scale_degree": 1, "onset": "1/2", "duration": "1/2", "velocity": 88}, {"type": "note", "name": "E", "pitch": "E2", "scale_degree": 1, "onset": "1/1", "duration": "1/2", "velocity": 69}, {"type": "note", "name": "E", "pitch": "E3", "scale_degree": 1, "onset": "3/2", "duration": "1/2", "velocity": 83}, {"type": "note", "name": "E-", "pitch": "E-2", "scale_degree": 0, "onset": "2/1", "duration": "1/2", "velocity": 68}, {"type": "note", "name": "E-", "pitch": "E-3", "scale_degree": 0, "onset": "5/2", "duration": "1/2", "velocity": 90}, {"type": "rest", "name": "Quarter Rest", "onset": "3/1", "duration": "1/1"}]}, {"measure_number": 7, "notes": [{"type": "note", "name": "C#", "pitch": "C#2", "scale_degree": 6, "onset": "0/1", "duration": "1/2", "velocity": 64}, {"type": "chord", "name": "C#m", "pitches": ["E5", "G#5", "C#3"], "function": "dominant", "roman": "vi", "scale_degrees": [1, 3, 6], "onset": "1/2", "duration": "1/2", "velocity": 75}, {"type": "chord", "name": "C#m", "pitches": ["E5", "B5", "C#2"], "function": "dominant", "roman": "vi7", "scale_degrees": [1, 5, 6], "onset": "1/1", "duration": "1/2", "velocity": 79}, {"type": "chord", "name": "C#m", "pitches": ["E5", "C#6", "C#3"], "function": "dominant", "roman": "vi", "scale_degrees": [1, 6, 6], "onset": "3/2", "duration": "1/2", "velocity": 84}, {"type": "chord", "name": "E(other)", "pitches": ["E5", "B5"], "function": "tonic", "roman": "i5", "scale_degrees": [1, 5], "onset": "2/1", "duration": "1/1", "velocity": 72}, {"type": "chord", "name": "A(other)", "pitches": ["E-5", "A5", "B1"], "function": "subdominant", "roman": "ivo7b4", "scale_degrees": [1, 4, 5], "onset": "3/1", "duration": "1/2", "velocity": 68}, {"type": "chord", "name": "A(other)", "pitches": ["E-5", "A5", "B2"], "function": "subdominant", "roman": "ivo7b4", "scale_degrees": [1, 4, 5], "onset": "7/2", "duration": "1/2", "velocity": 78}, {"type": "rest", "name": "Half Rest", "onset": "0/1", "duration": "2/1"}, {"type": "note", "name": "B", "pitch": "B1", "scale_degree": 5, "onset": "2/1", "duration": "1/2", "velocity": 70}, {"type": "note", "name": "B", "pitch": "B2", "scale_degree": 5, "onset": "5/2", "duration": "1/2", "velocity": 83}, {"type": "rest", "name": "Quarter Rest", "onset": "3/1", "duration": "1/1"}]}, {"measure_number": 8, "notes": [{"type": "chord", "name": "E", "pitches": ["E5", "G#5"], "function": "tonic", "roman": "I", "scale_degrees": [1, 3], "onset": "0/1", "duration": "1/1", "velocity": 72}, {"type": "chord", "name": "G#m", "pitches": ["G#5", "B5"], "function": "subdominant", "roman": "iii", "scale_degrees": [3, 5], "onset": "1/1", "duration": "1/1", "velocity": 81}, {"type": "chord", "name": "A(other)", "pitches": ["E5", "A5"], "function": "subdominant", "roman": "iv4", "scale_degrees": [1, 4], "onset": "2/1", "duration": "1/1", "velocity": 70}, {"type": "chord", "name": "E", "pitches": ["E5", "G#5"], "function": "tonic", "roman": "I", "scale_degrees": [1, 3], "onset": "3/1", "duration": "1/1", "velocity": 71}, {"type": "note", "name": "A", "pitch": "A1", "scale_degree": 4, "onset": "0/1", "duration": "1/2", "velocity": 67}, {"type": "note", "name": "A", "pitch": "A2", "scale_degree": 4, "onset": "1/2", "duration": "1/2", "velocity": 85}, {"type": "note", "name": "A", "pitch": "A1", "scale_degree": 4, "onset": "1/1", "duration": "1/2", "velocity": 66}, {"type": "note", "name": "A", "pitch": "A2", "scale_degree": 4, "onset": "3/2", "duration": "1/2", "velocity": 79}, {"type": "note", "name": "A", "pitch": "A1", "scale_degree": 4, "onset": "2/1", "duration": "1/2", "velocity": 73}, {"type": "note", "name": "A", "pitch": "A2", "scale_degree": 4, "onset": "5/2", "duration": "1/2", "velocity": 85}, {"type": "note", "name": "A", "pitch": "A1", "scale_degree": 4, "onset": "3/1", "duration": "1/2", "velocity": 67}, {"type": "note", "name": "A", "pitch": "A2", "scale_degree": 4, "onset": "7/2", "duration": "1/2", "velocity": 87}]}, {"measure_number": 9, "notes": [{"type": "note", "name": "B", "pitch": "B1", "scale_degree": 5, "onset": "0/1", "duration": "1/2", "velocity": 72}, {"type": "chord", "name": "E-(other)", "pitches": ["B4", "E-5", "F#5", "B2"], "function": "other", "roman": "bi+#54", "scale_degrees": [5, 1, 2, 5], "onset": "1/2", "duration": "1/2", "velocity": 76}, {"type": "chord", "name": "E-(other)", "pitches": ["B4", "E-5", "F#5", "B1"], "function": "other", "roman": "bi+#54", "scale_degrees": [5, 1, 2, 5], "onset": "1/1", "duration": "1/2", "velocity": 74}, {"type": "chord", "name": "E-(other)", "pitches": ["B4", "E-5", "F#5", "B2"], "function": "other", "roman": "bi+#54", "scale_degrees": [5, 1, 2, 5], "onset": "3/2", "duration": "1/2", "velocity": 82}, {"type": "note", "name": "B", "pitch": "B1", "scale_degree": 5, "onset": "2/1", "duration": "1/2", "velocity": 71}, {"type": "chord", "name": "E-(other)", "pitches": ["B4", "E-5", "F#5", "B2"], "function": "other", "roman": "bi+#54", "scale_degrees": [5, 1, 2, 5], "onset": "5/2", "duration": "1/2", "velocity": 72}, {"type": "chord", "name": "E-(other)", "pitches": ["B4", "E-5", "F#5", "B1"], "function": "other", "roman": "bi+#54", "scale_degrees": [5, 1, 2, 5], "onset": "3/1", "duration": "1/2", "velocity": 73}, {"type": "chord", "name": "E-(other)", "pitches": ["B4", "E-5", "F#5", "B2"], "function": "other", "roman": "bi+#54", "scale_degrees": [5, 1, 2, 5], "onset": "7/2", "duration": "1/2", "velocity": 81}]}, {"measure_number": 10, "notes": [{"type": "note", "name": "E", "pitch": "E2", "scale_degree": 1, "onset": "0/1", "duration": "1/2", "velocity": 70}, {"type": "chord", "name": "E", "pitches": ["E5", "G#5", "E3"], "function": "tonic", "roman": "I", "scale_degrees": [1, 3, 1], "onset": "1/2", "duration": "1/2", "velocity": 73}, {"type": "chord", "name": "F#(other)", "pitches": ["E-5", "F#5", "E2"], "function": "subdominant", "roman": "ii2", "scale_degrees": [1, 2, 1], "onset": "1/1", "duration": "1/2", "velocity": 71}, {"type": "chord", "name": "E(other)", "pitches": ["B4", "E5", "E3"], "function": "tonic", "roman": "i5", "scale_degrees": [5, 1, 1], "onset": "3/2", "duration": "1/2", "velocity": 78}, {"type": "note", "name": "B", "pitch": "B1", "scale_degree": 5, "onset": "2/1", "duration": "1/2", "velocity": 64}, {"type": "chord", "name": "E(other)", "pitches": ["B4", "E5", "B2"], "function": "tonic", "roman": "i4", "scale_degrees": [5, 1, 5], "onset": "5/2", "duration": "1/2", "velocity": 75}, {"type": "chord", "name": "E-(other)", "pitches": ["B4", "E-5", "B1"], "function": "other", "roman": "bi+4", "scale_degrees": [5, 1, 5], "onset": "3/1", "duration": "1/2", "velocity": 71}, {"type": "chord", "name": "E(other)", "pitches": ["B4", "E5", "B2"], "function": "tonic", "roman": "i4", "scale_degrees": [5, 1, 5], "onset": "7/2", "duration": "1/2", "velocity": 81}]}, {"measure_number": 11, "notes": [{"type": "note", "name": "C#", "pitch": "C#2", "scale_degree": 6, "onset": "0/1", "duration": "1/2", "velocity": 68}, {"type": "chord", "name": "C#m", "pitches": ["B4", "E5", "C#3"], "function": "dominant", "roman": "vi7", "scale_degrees": [5, 1, 6], "onset": "1/2", "duration": "1/2", "velocity": 73}, {"type": "chord", "name": "C#(other)", "pitches": ["B4", "E-5", "C#2"], "function": "dominant", "roman": "vi7b3", "scale_degrees": [5, 1, 6], "onset": "1/1", "duration": "1/2", "velocity": 70}, {"type": "chord", "name": "C#m", "pitches": ["B4", "E5", "C#3"], "function": "dominant", "roman": "vi7", "scale_degrees": [5, 1, 6], "onset": "3/2", "duration": "1/2", "velocity": 80}, {"type": "chord", "name": "E-(other)", "pitches": ["E-5", "G#5"], "function": "other", "roman": "bi#3", "scale_degrees": [1, 3], "onset": "2/1", "duration": "1/1", "velocity": 84}, {"type": "chord", "name": "F#(other)", "pitches": ["E-5", "F#5"], "function": "subdominant", "roman": "ii2", "scale_degrees": [1, 2], "onset": "3/1", "duration": "1/1", "velocity": 69}, {"type": "rest", "name": "Half Rest", "onset": "0/1", "duration": "2/1"}, {"type": "note", "name": "C#", "pitch": "C#2", "scale_degree": 6, "onset": "2/1", "duration": "1/2", "velocity": 70}, {"type": "note", "name": "B", "pitch": "B2", "scale_degree": 5, "onset": "5/2", "duration": "1/2", "velocity": 85}, {"type": "note", "name": "B", "pitch": "B1", "scale_degree": 5, "onset": "3/1", "duration": "1/2", "velocity": 67}, {"type": "note", "name": "B", "pitch": "B2", "scale_degree": 5, "onset": "7/2", "duration": "1/2", "velocity": 89}]}, {"measure_number": 12, "notes": [{"type": "note", "name": "E", "pitch": "E2", "scale_degree": 1, "onset": "0/1", "duration": "1/2", "velocity": 72}, {"type": "chord", "name": "E", "pitches": ["E5", "G#5", "E3"], "function": "tonic", "roman": "I", "scale_degrees": [1, 3, 1], "onset": "1/2", "duration": "1/2", "velocity": 78}, {"type": "chord", "name": "F#(other)", "pitches": ["E-5", "F#5", "E2"], "function": "subdominant", "roman": "ii2", "scale_degrees": [1, 2, 1], "onset": "1/1", "duration": "1/2", "velocity": 71}, {"type": "chord", "name": "E(other)", "pitches": ["B4", "E5", "E3"], "function": "tonic", "roman": "i5", "scale_degrees": [5, 1, 1], "onset": "3/2", "duration": "1/2", "velocity": 75}, {"type": "note", "name": "B", "pitch": "B1", "scale_degree": 5, "onset": "2/1", "duration": "1/2", "velocity": 68}, {"type": "chord", "name": "C#(other)", "pitches": ["C#5", "B2"], "function": "dominant", "roman": "vi2", "scale_degrees": [6, 5], "onset": "5/2", "duration": "1/2", "velocity": 78}, {"type": "chord", "name": "E-(other)", "pitches": ["B4", "E-5", "B1"], "function": "other", "roman": "bi+4", "scale_degrees": [5, 1, 5], "onset": "3/1", "duration": "1/2", "velocity": 79}, {"type": "chord", "name": "E(other)", "pitches": ["B4", "E5", "B2"], "function": "tonic", "roman": "i4", "scale_degrees": [5, 1, 5], "onset": "7/2", "duration": "1/2", "velocity": 83}]}, {"measure_number": 13, "notes": [{"type": "note", "name": "C#", "pitch": "C#2", "scale_degree": 6, "onset": "0/1", "duration": "1/2", "velocity": 70}, {"type": "chord", "name": "C#m", "pitches": ["B4", "E5", "C#3"], "function": "dominant", "roman": "vi7", "scale_degrees": [5, 1, 6], "onset": "1/2", "duration": "1/2", "velocity": 71}, {"type": "chord", "name": "C#(other)", "pitches": ["B4", "E-5", "C#2"], "function": "dominant", "roman": "vi7b3", "scale_degrees": [5, 1, 6], "onset": "1/1", "duration": "1/2", "velocity": 69}, {"type": "chord", "name": "C#m", "pitches": ["B4", "E5", "C#3"], "function": "dominant", "roman": "vi7", "scale_degrees": [5, 1, 6], "onset": "3/2", "duration": "1/2", "velocity": 81}, {"type": "chord", "name": "E", "pitches": ["E5", "G#5"], "function": "tonic", "roman": "I", "scale_degrees": [1, 3], "onset": "2/1", "duration": "1/1", "velocity": 87}, {"type": "chord", "name": "E(other)", "pitches": ["E5", "B5"], "function": "tonic", "roman

In [16]:
trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = train_set,
    eval_dataset = None,
    # data_collator = DataCollatorForSeq2Seq(tokenizer = tokenizer),
    
    # packing = False, # Can make training 5x faster for short sequences.
    args = SFTConfig(
        dataset_text_field = "prompt",
        per_device_train_batch_size = 2,
        gradient_accumulation_steps = 4, # Fixed major bug in latest Unsloth
        warmup_steps = 5,
        # num_train_epochs = 1, # Set this for 1 full training run.
        max_seq_length = max_seq_length,
        dataset_num_proc = 8,
        max_steps = 60,
        learning_rate = 2e-4,
        fp16 = not is_bfloat16_supported(),
        bf16 = is_bfloat16_supported(),
        logging_steps = 1,
        optim = "adamw_8bit", # Save more memory
        weight_decay = 0.01,
        lr_scheduler_type = "linear",
        seed = 3407,
        output_dir = "outputs",
        report_to = "none", # Use this for WandB etc
    ),
)

Unsloth: Tokenizing ["prompt"] (num_proc=8):   0%|          | 0/13904 [00:00<?, ? examples/s]

In [ ]:

# trainer = train_on_responses_only(
#     trainer,
#     instruction_part = "<|im_start|>user\n",
#     response_part = "<|im_start|>assistant\n",
# )

In [ ]:
# tokenizer.decode(trainer.train_dataset[1]["input_ids"])

'<|im_start|>system\nYou are Qwen, created by Alibaba Cloud. You are a helpful assistant.<|im_end|>\n<|im_start|>user\nA classical piece that could be part of a film soundtrack, this short song features a recorder playing a relaxing melody. With a tempo of 74 beats per minute, it moves at an Andante pace in 4/4 time. The key is C# major, and the chord progression includes C#, Fm, and Ab. The overall mood is emotional and well-suited for a dramatic or documentary-style film.<|im_end|>\n<|im_start|>assistant\n{"metadata": {"bpm": 74, "time_signature": "4/4", "key_signature": "C# major"}, "chords": ["C#", "Fm", "Ab"], "tracks": [{"name": "track_0", "instrument": "unknown", "measures": [{"measure_number": 1, "notes": [{"type": "chord", "name": "G#(other)", "pitches": ["F4", "G#4"], "function": "dominant", "roman": "v2", "scale_degrees": [4, 5], "onset": "0/1", "duration": "4/1", "velocity": 64}]}, {"measure_number": 2, "notes": [{"type": "chord", "name": "G#(other)", "pitches": ["F4", "G#4"], "function": "dominant", "roman": "v2", "scale_degrees": [4, 5], "onset": "0/1", "duration": "1/2", "velocity": 64}, {"type": "rest", "name": "Eighth Rest", "onset": "1/2", "duration": "1/2"}, {"type": "chord", "name": "G#(other)", "pitches": ["F4", "G#4"], "function": "dominant", "roman": "v2", "scale_degrees": [4, 5], "onset": "1/1", "duration": "3/2", "velocity": 64}, {"type": "note", "name": "C", "pitch": "C5", "scale_degree": 0, "onset": "5/2", "duration": "1/2", "velocity": 64}, {"type": "note", "name": "C#", "pitch": "C#5", "scale_degree": 1, "onset": "3/1", "duration": "1/1", "velocity": 64}, {"type": "rest", "name": "Triple Dotted Half (3 3/4 QL) Rest", "onset": "0/1", "duration": "15/4"}, {"type": "note", "name": "C", "pitch": "C5", "scale_degree": 0, "onset": "15/4", "duration": "1/4", "velocity": 64}]}, {"measure_number": 3, "notes": [{"type": "note", "name": "G#", "pitch": "G#4", "scale_degree": 5, "onset": "0/1", "duration": "1/1", "velocity": 64}, {"type": "note", "name": "F", "pitch": "F4", "scale_degree": 0, "onset": "1/1", "duration": "1/1", "velocity": 64}, {"type": "chord", "name": "C(other)", "pitches": ["G#4", "C5"], "function": "other", "roman": "bi+4", "scale_degrees": [5, 1], "onset": "2/1", "duration": "2/1", "velocity": 64}, {"type": "rest", "name": "Dotted Eighth Rest", "onset": "0/1", "duration": "3/4"}, {"type": "note", "name": "G#", "pitch": "G#4", "scale_degree": 5, "onset": "3/4", "duration": "1/4", "velocity": 64}, {"type": "rest", "name": "Half tied to Dotted Eighth (2 3/4 total QL) Rest", "onset": "1/1", "duration": "11/4"}, {"type": "note", "name": "C", "pitch": "C5", "scale_degree": 0, "onset": "15/4", "duration": "1/4", "velocity": 64}]}, {"measure_number": 4, "notes": [{"type": "note", "name": "G#", "pitch": "G#4", "scale_degree": 5, "onset": "0/1", "duration": "1/1", "velocity": 64}, {"type": "note", "name": "B-", "pitch": "B-4", "scale_degree": 0, "onset": "1/1", "duration": "1/3", "velocity": 64}, {"type": "note", "name": "C", "pitch": "C5", "scale_degree": 0, "onset": "4/3", "duration": "1/3", "velocity": 64}, {"type": "note", "name": "E-", "pitch": "E-5", "scale_degree": 0, "onset": "5/3", "duration": "1/3", "velocity": 64}, {"type": "rest", "name": "Eighth Rest", "onset": "2/1", "duration": "1/2"}, {"type": "note", "name": "E-", "pitch": "E-5", "scale_degree": 0, "onset": "5/2", "duration": "1/2", "velocity": 64}, {"type": "note", "name": "F", "pitch": "F5", "scale_degree": 0, "onset": "3/1", "duration": "1/1", "velocity": 64}]}, {"measure_number": 5, "notes": [{"type": "note", "name": "C#", "pitch": "C#5", "scale_degree": 1, "onset": "0/1", "duration": "1/1", "velocity": 64}, {"type": "note", "name": "C", "pitch": "C5", "scale_degree": 0, "onset": "1/1", "duration": "1/1", "velocity": 64}, {"type": "note", "name": "G#", "pitch": "G#4", "scale_degree": 5, "onset": "2/1", "duration": "2/1", "velocity": 64}, {"type": "rest", "name": "Double Dotted Quarter Rest", "onset": "0/1", "duration": "7/4"}, {"type": "note", "name": "C", "pitch": "C5", "scale_degree": 0, "onset": "7/4", "duration": "1/4", "velocity": 64}, {"type": "rest", "name": "Double Dotted Quarter Rest", "onset": "2/1", "duration": "7/4"}, {"type": "note", "name": "F", "pitch": "F5", "scale_degree": 0, "onset": "15/4", "duration": "1/4", "velocity": 64}]}, {"measure_number": 6, "notes": [{"type": "note", "name": "C", "pitch": "C5", "scale_degree": 0, "onset": "0/1", "duration": "1/1", "velocity": 64}, {"type": "note", "name": "G#", "pitch": "G#4", "scale_degree": 5, "onset": "1/1", "duration": "1/1", "velocity": 64}, {"type": "note", "name": "F", "pitch": "F4", "scale_degree": 0, "onset": "2/1", "duration": "2/1", "velocity": 64}, {"type": "rest", "name": "Triple Dotted Half (3 3/4 QL) Rest", "onset": "0/1", "duration": "15/4"}, {"type": "note", "name": "G", "pitch": "G5", "scale_degree": 0, "onset": "15/4", "duration": "1/4", "velocity": 64}]}, {"measure_number": 7, "notes": [{"type": "note", "name": "C#", "pitch": "C#5", "scale_degree": 1, "onset": "0/1", "duration": "1/1", "velocity": 64}, {"type": "note", "name": "C", "pitch": "C5", "scale_degree": 0, "onset": "1/1", "duration": "1/1", "velocity": 64}, {"type": "note", "name": "B-", "pitch": "B-4", "scale_degree": 0, "onset": "2/1", "duration": "2/1", "velocity": 64}, {"type": "rest", "name": "Triple Dotted Half (3 3/4 QL) Rest", "onset": "0/1", "duration": "15/4"}, {"type": "note", "name": "E-", "pitch": "E-5", "scale_degree": 0, "onset": "15/4", "duration": "1/4", "velocity": 64}]}, {"measure_number": 8, "notes": [{"type": "note", "name": "B", "pitch": "B4", "scale_degree": 0, "onset": "0/1", "duration": "1/1", "velocity": 64}, {"type": "note", "name": "B-", "pitch": "B-4", "scale_degree": 0, "onset": "1/1", "duration": "1/1", "velocity": 64}, {"type": "note", "name": "G#", "pitch": "G#4", "scale_degree": 5, "onset": "2/1", "duration": "2/1", "velocity": 64}, {"type": "rest", "name": "Triple Dotted Half (3 3/4 QL) Rest", "onset": "0/1", "duration": "15/4"}, {"type": "note", "name": "C", "pitch": "C5", "scale_degree": 0, "onset": "15/4", "duration": "1/4", "velocity": 64}]}, {"measure_number": 9, "notes": [{"type": "note", "name": "G#", "pitch": "G#4", "scale_degree": 5, "onset": "0/1", "duration": "1/1", "velocity": 64}, {"type": "note", "name": "F", "pitch": "F4", "scale_degree": 0, "onset": "1/1", "duration": "2/1", "velocity": 64}, {"type": "rest", "name": "Quarter Rest", "onset": "3/1", "duration": "1/1"}]}, {"measure_number": 10, "notes": [{"type": "rest", "name": "Dotted Quarter Rest", "onset": "0/1", "duration": "3/2"}, {"type": "note", "name": "C#", "pitch": "C#5", "scale_degree": 1, "onset": "3/2", "duration": "1/4", "velocity": 64}, {"type": "note", "name": "E-", "pitch": "E-5", "scale_degree": 0, "onset": "7/4", "duration": "1/4", "velocity": 64}, {"type": "note", "name": "F", "pitch": "F5", "scale_degree": 0, "onset": "2/1", "duration": "1/1", "velocity": 64}, {"type": "chord", "name": "F(other)", "pitches": ["G5", "F4", "C5"], "function": "other", "roman": "biv52", "scale_degrees": [5, 4, 1], "onset": "3/1", "duration": "1/2", "velocity": 64}, {"type": "rest", "name": "Eighth Rest", "onset": "7/2", "duration": "1/2"}, {"type": "rest", "name": "Half Rest", "onset": "0/1", "duration": "2/1"}, {"type": "chord", "name": "F(other)", "pitches": ["F4", "C5"], "function": "other", "roman": "biv5", "scale_degrees": [4, 1], "onset": "2/1", "duration": "1/2", "velocity": 64}, {"type": "rest", "name": "Dotted Eighth Rest", "onset": "5/2", "duration": "3/4"}, {"type": "note", "name": "G#", "pitch": "G#5", "scale_degree": 5, "onset": "13/4", "duration": "3/4", "velocity": 64}]}, {"measure_number": 11, "notes": [{"type": "chord", "name": "F(other)", "pitches": ["G5", "F4", "C5"], "function": "other", "roman": "biv52", "scale_degrees": [5, 4, 1], "onset": "0/1", "duration": "1/2", "velocity": 64}, {"type": "note", "name": "G#", "pitch": "G#5", "scale_degree": 5, "onset": "1/2", "duration": "1/1", "velocity": 64}, {"type": "note", "name": "G", "pitch": "G5", "scale_degree": 0, "onset": "3/2", "duration": "1/4", "velocity": 64}, {"type": "note", "name": "F", "pitch": "F5", "scale_degree": 0, "onset": "7/4", "duration": "1/4", "velocity": 64}, {"type": "note", "name": "F", "pitch": "F5", "scale_degree": 0, "onset": "2/1", "duration": "1/2", "velocity": 64}, {"type": "chord", "name": "E-", "pitches": ["E-5", "G4"], "function": "other", "roman": "bbIII#86", "scale_degrees": [3, 5], "onset": "5/2", "duration": "1/2", "velocity": 64}, {"type": "chord", "name": "F(other)", "pitches": ["C5", "F4"], "function": "other", "roman": "biv5", "scale_degrees": [1, 4], "onset": "3/1", "duration": "1/1", "velocity": 64}, {"type": "rest", "name": "16th Rest", "onset": "0/1", "duration": "1/4"}, {"type": "note", "name": "G#", "pitch": "G#5", "scale_degree": 5, "onset": "1/4", "duration": "1/4", "velocity": 64}, {"type": "rest", "name": "16th Rest", "onset": "1/2", "duration": "1/4"}, {"type": "note", "name": "C", "pitch": "C5", "scale_degree": 0, "onset": "3/4", "duration": "1/4", "velocity": 64}, {"type": "note", "name": "G#", "pitch": "G#4", "scale_degree": 5, "onset": "1/1", "duration": "3/2", "velocity": 64}, {"type": "rest", "name": "16th Rest", "onset": "5/2", "duration": "1/4"}, {"type": "note", "name": "C#", "pitch": "C#5", "scale_degree": 1, "onset": "11/4", "duration": "1/4", "velocity": 64}, {"type": "rest", "name": "Quarter Rest", "onset": "3/1", "duration": "1/1"}]}, {"measure_number": 12, "notes": [{"type": "chord", "name": "C(other)", "pitches": ["G#5", "C5"], "function": "other", "roman": "bi+#5", "scale_degrees": [5, 1], "onset": "0/1", "duration": "3/4", "velocity": 64}, {"type": "note", "name": "B-", "pitch": "B-4", "scale_degree": 0, "onset": "3/4", "duration": "1/4", "velocity": 64}, {"type": "note", "name": "C#", "pitch": "C#5", "scale_degree": 1, "onset": "1/1", "duration": "2/1", "velocity": 64}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "G#4"], "function": "other", "roman": "bi+#84", "scale_degrees": [1, 5], "onset": "3/1", "duration": "1/1", "velocity": 64}, {"type": "rest", "name": "Quarter Rest", "onset": "0/1", "duration": "1/1"}, {"type": "note", "name": "G#", "pitch": "G#4", "scale_degree": 5, "onset": "1/1", "duration": "1/4", "velocity": 64}, {"type": "note", "name": "B-", "pitch": "B-4", "scale_degree": 0, "onset": "5/4", "duration": "1/4", "velocity": 64}, {"type": "note", "name": "C", "pitch": "C5", "scale_degree": 0, "onset": "3/2", "duration": "1/2", "velocity": 64}, {"type": "note", "name": "G#", "pitch": "G#4", "scale_degree": 5, "onset": "2/1", "duration": "1/1", "velocity": 64}, {"type": "rest", "name": "Dotted Eighth Rest", "onset": "3/1", "duration": "3/4"}, {"type": "chord", "name": "F(other)", "pitches": ["F5", "C#5"], "function": "other", "roman": "biv+#84", "scale_degrees": [4, 1], "onset": "15/4", "duration": "1/4", "velocity": 64}, {"type": "rest", "name": "Double Dotted Quarter Rest", "onset": "0/1", "duration": "7/4"}, {"type": "note", "name": "C", "pitch": "C5", "scale_degree": 0, "onset": "7/4", "duration": "1/4", "velocity": 64}, {"type": "rest", "name": "Dotted Eighth Rest", "onset": "2/1", "duration": "3/4"}, {"type": "note", "name": "B-", "pitch": "B-4", "scale_degree": 0, "onset": "11/4", "duration": "1/4", "velocity": 64}, {"type": "rest", "name": "Quarter Rest", "onset": "3/1", "duration": "1/1"}]}, {"measure_number": 13, "notes": [{"type": "chord", "name": "C(other)", "pitches": ["C5", "G#4"], "function": "other", "roman": "bi+#84", "scale_degrees": [1, 5], "onset": "0/1", "duration": "3/1", "velocity": 64}, {"type": "rest", "name": "Dotted Eighth Rest", "onset": "3/1", "duration": "3/4"}, {"type": "note", "name": "E-", "pitch": "E-5", "scale_degree": 0, "onset": "15/4", "duration": "1/4", "velocity": 64}]}, {"measure_number": 14, "notes": [{"type": "note", "name": "F", "pitch": "F5", "scale_degree": 0, "onset": "0/1", "duration": "1/1", "velocity": 64}, {"type": "note", "name": "E-", "pitch": "E-5", "scale_degree": 0, "onset": "1/1", "duration": "1/2", "velocity": 64}, {"type": "note", "name": "C#", "pitch": "C#5", "scale_degree": 1, "onset": "3/2", "duration": "1/2", "velocity": 64}, {"type": "note", "name": "C", "pitch": "C5", "scale_degree": 0, "onset": "2/1", "duration": "1/1", "velocity": 64}, {"type": "note", "name": "C#", "pitch": "C#5", "scale_degree": 1, "onset": "3/1", "duration": "1/3", "velocity": 64}, {"type": "note", "name": "E-", "pitch": "E-5", "scale_degree": 0, "onset": "10/3", "duration": "1/3", "velocity": 64}, {"type": "note", "name": "F", "pitch": "F5", "scale_degree": 0, "onset": "11/3", "duration": "1/3", "velocity": 64}]}, {"measure_number": 15, "notes": [{"type": "chord", "name": "F(other)", "pitches": ["F4", "C5"], "function": "other", "roman": "biv5", "scale_degrees": [4, 1], "onset": "0/1", "duration": "1/2", "velocity": 64}, {"type": "note", "name": "F", "pitch": "F5", "scale_degree": 0, "onset": "0/1", "duration": "5/12", "velocity": 64}, {"type": "rest", "name": "Eighth Rest", "onset": "1/2", "duration": "1/2"}, {"type": "chord", "name": "F(other)", "pitches": ["C5", "F4", "G#4"], "function": "other", "roman": "biv5#2", "scale_degrees": [1, 4, 5], "onset": "1/1", "duration": "1/2", "velocity": 64}, {"type": "rest", "name": "Eighth Rest", "onset": "3/2", "duration": "1/2"}, {"type": "chord", "name": "F(other)", "pitches": ["C5", "F4"], "function": "other", "roman": "biv5", "scale_degrees": [1, 4], "onset": "2/1", "duration": "1/2", "velocity": 64}, {"type": "rest", "name": "Eighth Rest", "onset": "5/2", "duration": "1/2"}, {"type": "note", "name": "C", "pitch": "C5", "scale_degree": 0, "onset": "3/1", "duration": "1/1", "velocity": 64}, {"type": "rest", "name": "Dotted Half Rest", "onset": "0/1", "duration": "3/1"}, {"type": "note", "name": "F", "pitch": "F4", "scale_degree": 0, "onset": "3/1", "duration": "1/2", "velocity": 64}, {"type": "rest", "name": "Eighth Rest", "onset": "7/2", "duration": "1/2"}]}, {"measure_number": 16, "notes": [{"type": "note", "name": "C", "pitch": "C5", "scale_degree": 0, "onset": "0/1", "duration": "1/2", "velocity": 64}, {"type": "chord", "name": "B-(other)", "pitches": ["B-4", "F4"], "function": "other", "roman": "bbvii#84", "scale_degrees": [7, 4], "onset": "1/2", "duration": "1/2", "velocity": 64}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "G#4"], "function": "other", "roman": "bi+#84", "scale_degrees": [1, 5], "onset": "1/1", "duration": "1/2", "velocity": 64}, {"type": "chord", "name": "C#(other)", "pitches": ["C#5", "C#5"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "3/2", "duration": "3/2", "velocity": 64}, {"type": "note", "name": "F", "pitch": "F4", "scale_degree": 0, "onset": "3/1", "duration": "1/2", "velocity": 64}, {"type": "note", "name": "F", "pitch": "F5", "scale_degree": 0, "onset": "7/2", "duration": "1/2", "velocity": 64}]}, {"measure_number": 17, "notes": [{"type": "chord", "name": "E-(other)", "pitches": ["G5", "G#4", "E-5"], "function": "other", "roman": "bbIII##86", "scale_degrees": [5, 5, 3], "onset": "0/1", "duration": "1/2", "velocity": 64}, {"type": "note", "name": "B-", "pitch": "B-5", "scale_degree": 0, "onset": "1/2", "duration": "1/1", "velocity": 64}, {"type": "rest", "name": "Eighth Rest", "onset": "3/2", "duration": "1/2"}, {"type": "chord", "name": "F(other)", "pitches": ["G#5", "F4", "C5"], "function": "other", "roman": "biv5#2", "scale_degrees": [5, 4, 1], "onset": "2/1", "duration": "1/2", "velocity": 64}, {"type": "rest", "name": "Eighth Rest", "onset": "5/2", "duration": "1/2"}, {"type": "chord", "name": "F(other)", "pitches": ["G#5", "F4", "C5"], "function": "other", "roman": "biv5#2", "scale_degrees": [5, 4, 1], "onset": "3/1", "duration": "1/2", "velocity": 64}, {"type": "rest", "name": "Eighth Rest", "onset": "7/2", "duration": "1/2"}, {"type": "rest", "name": "Quarter Rest", "onset": "0/1", "duration": "1/1"}, {"type": "chord", "name": "C#(other)", "pitches": ["G#4", "C#5"], "function": "tonic", "roman": "i4", "scale_degrees": [5, 1], "onset": "1/1", "duration": "1/2", "velocity": 64}, {"type": "rest", "name": "Half tied to Eighth (2 1/2 total QL) Rest", "onset": "3/2", "duration": "5/2"}]}, {"measure_number": 18, "notes": [{"type": "note", "name": "G#", "pitch": "G#5", "scale_degree": 5, "onset": "0/1", "duration": "2/1", "velocity": 64}, {"type": "note", "name": "F", "pitch": "F4", "scale_degree": 0, "onset": "2/1", "duration": "1/2", "velocity": 64}, {"type": "note", "name": "G#", "pitch": "G#5", "scale_degree": 5, "onset": "5/2", "duration": "1/4", "velocity": 64}, {"type": "note", "name": "G#", "pitch": "G#5", "scale_degree": 5, "onset": "11/4", "duration": "1/4", "velocity": 64}, {"type": "note", "name": "G#", "pitch": "G#5", "scale_degree": 5, "onset": "3/1", "duration": "1/1", "velocity": 64}, {"type": "note", "name": "B-", "pitch": "B-4", "scale_degree": 0, "onset": "0/1", "duration": "1/2", "velocity": 64}, {"type": "rest", "name": "Eighth Rest", "onset": "1/2", "duration": "1/2"}, {"type": "note", "name": "G#", "pitch": "G#4", "scale_degree": 5, "onset": "1/1", "duration": "1/2", "velocity": 64}, {"type": "note", "name": "G", "pitch": "G4", "scale_degree": 0, "onset": "3/2", "duration": "1/2", "velocity": 64}, {"type": "rest", "name": "Quarter Rest", "onset": "2/1", "duration": "1/1"}, {"type": "note", "name": "F", "pitch": "F4", "scale_degree": 0, "onset": "3/1", "duration": "1/2", "velocity": 64}, {"type": "rest", "name": "Eighth Rest", "onset": "7/2", "duration": "1/2"}]}, {"measure_number": 19, "notes": [{"type": "chord", "name": "F(other)", "pitches": ["E-6", "F4", "C5"], "function": "other", "roman": "bivb75", "scale_degrees": [3, 4, 1], "onset": "0/1", "duration": "1/2", "velocity": 64}, {"type": "rest", "name": "Eighth Rest", "onset": "1/2", "duration": "1/2"}, {"type": "chord", "name": "F(other)", "pitches": ["C6", "F4", "C5"], "function": "other", "roman": "biv5", "scale_degrees": [1, 4, 1], "onset": "1/1", "duration": "1/2", "velocity": 64}, {"type": "note", "name": "C", "pitch": "C6", "scale_degree": 0, "onset": "3/2", "duration": "1/4", "velocity": 64}, {"type": "note", "name": "C", "pitch": "C6", "scale_degree": 0, "onset": "7/4", "duration": "1/4", "velocity": 64}, {"type": "note", "name": "C", "pitch": "C6", "scale_degree": 0, "onset": "2/1", "duration": "1/1", "velocity": 64}, {"type": "rest", "name": "Eighth Rest", "onset": "3/1", "duration": "1/2"}, {"type": "note", "name": "G#", "pitch": "G#5", "scale_degree": 5, "onset": "7/2", "duration": "1/2", "velocity": 64}, {"type": "rest", "name": "Half Rest", "onset": "0/1", "duration": "2/1"}, {"type": "chord", "name": "F(other)", "pitches": ["F4", "C5"], "function": "other", "roman": "biv5", "scale_degrees": [4, 1], "onset": "2/1", "duration": "2/1", "velocity": 64}]}, {"measure_number": 20, "notes": [{"type": "chord", "name": "G#(other)", "pitches": ["G#5", "F5"], "function": "dominant", "roman": "vb82", "scale_degrees": [5, 4], "onset": "0/1", "duration": "1/4", "velocity": 64}, {"type": "chord", "name": "C#(other)", "pitches": ["G5", "C#5"], "function": "tonic", "roman": "iob5'

In [ ]:
# space = tokenizer(" ", add_special_tokens = False).input_ids[0]
# tokenizer.decode([space if x == -100 else x for x in trainer.train_dataset[5]["labels"]])

'                                                                                                         {"metadata": {"bpm": 175, "time_signature": "2/4", "key_signature": "F# major"}, "chords": ["C#", "F#"], "tracks": [{"name": "Piano 1", "instrument": "Pno", "measures": [{"measure_number": 1, "notes": [{"type": "note", "name": "G#", "pitch": "G#3", "scale_degree": 2, "onset": "0/1", "duration": "3/4", "velocity": 92}, {"type": "rest", "name": "16th Rest", "onset": "3/4", "duration": "1/4"}, {"type": "chord", "name": "C#(other)", "pitches": ["C#6", "C#5"], "function": "dominant", "roman": "v", "scale_degrees": [5, 5], "onset": "1/1", "duration": "1/4", "velocity": 76}, {"type": "rest", "name": "16th Rest", "onset": "5/4", "duration": "1/4"}, {"type": "note", "name": "C#", "pitch": "C#5", "scale_degree": 5, "onset": "3/2", "duration": "1/4", "velocity": 64}, {"type": "rest", "name": "16th Rest", "onset": "7/4", "duration": "1/4"}, {"type": "note", "name": "C#", "pitch": "C#6", "scale_degree": 5, "onset": "0/1", "duration": "1/4", "velocity": 42}, {"type": "note", "name": "C#", "pitch": "C#5", "scale_degree": 5, "onset": "1/4", "duration": "1/4", "velocity": 54}, {"type": "chord", "name": "C#(other)", "pitches": ["C#5", "C#5"], "function": "dominant", "roman": "v", "scale_degrees": [5, 5], "onset": "1/2", "duration": "1/4", "velocity": 76}, {"type": "rest", "name": "16th Rest", "onset": "3/4", "duration": "1/4"}, {"type": "chord", "name": "B(other)", "pitches": ["B4", "C#4", "F4"], "function": "subdominant", "roman": "ivo7b4", "scale_degrees": [4, 5, 1], "onset": "1/1", "duration": "3/4", "velocity": 79}, {"type": "rest", "name": "16th Rest", "onset": "7/4", "duration": "1/4"}, {"type": "rest", "name": "Half Tuplet of 6/5ths (1 2/3 QL) Rest", "onset": "0/1", "duration": "5/3"}, {"type": "note", "name": "C#", "pitch": "C#5", "scale_degree": 5, "onset": "5/3", "duration": "1/3", "velocity": 80}]}, {"measure_number": 2, "notes": [{"type": "chord", "name": "C#(other)", "pitches": ["C#3", "C#6"], "function": "dominant", "roman": "v", "scale_degrees": [5, 5], "onset": "0/1", "duration": "1/4", "velocity": 77}, {"type": "note", "name": "C#", "pitch": "C#5", "scale_degree": 5, "onset": "1/4", "duration": "1/4", "velocity": 80}, {"type": "chord", "name": "Faug", "pitches": ["A4", "C#4", "F4", "C#5"], "function": "other", "roman": "bI+#864", "scale_degrees": [3, 5, 1, 5], "onset": "1/2", "duration": "1/4", "velocity": 71}, {"type": "rest", "name": "16th Rest", "onset": "3/4", "duration": "1/4"}, {"type": "chord", "name": "C#(other)", "pitches": ["C#6", "B3"], "function": "dominant", "roman": "v2", "scale_degrees": [5, 4], "onset": "1/1", "duration": "1/4", "velocity": 76}, {"type": "note", "name": "C#", "pitch": "C#5", "scale_degree": 5, "onset": "5/4", "duration": "1/4", "velocity": 71}, {"type": "chord", "name": "F(other)", "pitches": ["C#5", "G#4", "F4", "C#4", "C#5"], "function": "other", "roman": "bi+#54", "scale_degrees": [5, 2, 1, 5, 5], "onset": "3/2", "duration": "1/4", "velocity": 79}, {"type": "rest", "name": "16th Rest", "onset": "7/4", "duration": "1/4"}, {"type": "rest", "name": "Quarter Triplet (2/3 QL) Rest", "onset": "0/1", "duration": "2/3"}, {"type": "note", "name": "C#", "pitch": "C#5", "scale_degree": 5, "onset": "2/3", "duration": "1/3", "velocity": 91}, {"type": "rest", "name": "Quarter Rest", "onset": "1/1", "duration": "1/1"}]}, {"measure_number": 3, "notes": [{"type": "note", "name": "C#", "pitch": "C#6", "scale_degree": 5, "onset": "0/1", "duration": "1/4", "velocity": 62}, {"type": "note", "name": "C#", "pitch": "C#5", "scale_degree": 5, "onset": "1/4", "duration": "1/4", "velocity": 71}, {"type": "note", "name": "C#", "pitch": "C#5", "scale_degree": 5, "onset": "1/2", "duration": "1/4", "velocity": 59}, {"type": "rest", "name": "16th Rest", "onset": "3/4", "duration": "1/4"}, {"type": "chord", "name": "F#m", "pitches": ["A4", "F#4", "C#4"], "function": "tonic", "roman": "i64", "scale_degrees": [3, 1, 5], "onset": "1/1", "duration": "3/4", "velocity": 80}, {"type": "note", "name": "C#", "pitch": "C#5", "scale_degree": 5, "onset": "7/4", "duration": "1/4", "velocity": 80}, {"type": "note", "name": "F#", "pitch": "F#3", "scale_degree": 1, "onset": "0/1", "duration": "1/1", "velocity": 92}, {"type": "note", "name": "C#", "pitch": "C#6", "scale_degree": 5, "onset": "1/1", "duration": "1/4", "velocity": 61}, {"type": "note", "name": "C#", "pitch": "C#5", "scale_degree": 5, "onset": "5/4", "duration": "1/4", "velocity": 71}, {"type": "note", "name": "C#", "pitch": "C#5", "scale_degree": 5, "onset": "3/2", "duration": "1/4", "velocity": 72}, {"type": "rest", "name": "16th Rest", "onset": "7/4", "duration": "1/4"}, {"type": "rest", "name": "Quarter Triplet (2/3 QL) Rest", "onset": "0/1", "duration": "2/3"}, {"type": "note", "name": "C#", "pitch": "C#5", "scale_degree": 5, "onset": "2/3", "duration": "1/3", "velocity": 80}, {"type": "rest", "name": "Quarter Rest", "onset": "1/1", "duration": "1/1"}]}, {"measure_number": 4, "notes": [{"type": "chord", "name": "C#(other)", "pitches": ["C#6", "C#3"], "function": "dominant", "roman": "v", "scale_degrees": [5, 5], "onset": "0/1", "duration": "1/4", "velocity": 70}, {"type": "note", "name": "C#", "pitch": "C#5", "scale_degree": 5, "onset": "1/4", "duration": "1/4", "velocity": 71}, {"type": "chord", "name": "A", "pitches": ["C#4", "G#4", "A3", "C#5"], "function": "neapolitan", "roman": "bIII#7#3", "scale_degrees": [5, 2, 3, 5], "onset": "1/2", "duration": "1/4", "velocity": 70}, {"type": "note", "name": "C#", "pitch": "C#5", "scale_degree": 5, "onset": "3/4", "duration": "1/4", "velocity": 80}, {"type": "chord", "name": "F#(other)", "pitches": ["F#3", "C#6"], "function": "tonic", "roman": "i5", "scale_degrees": [1, 5], "onset": "1/1", "duration": "1/4", "velocity": 65}, {"type": "note", "name": "C#", "pitch": "C#5", "scale_degree": 5, "onset": "5/4", "duration": "1/4", "velocity": 80}, {"type": "chord", "name": "F#m", "pitches": ["C#4", "F#4", "C#5", "A3", "C#5"], "function": "tonic", "roman": "ib863", "scale_degrees": [5, 1, 5, 3, 5], "onset": "3/2", "duration": "1/4", "velocity": 71}, {"type": "rest", "name": "16th Rest", "onset": "7/4", "duration": "1/4"}]}, {"measure_number": 5, "notes": [{"type": "note", "name": "C#", "pitch": "C#6", "scale_degree": 5, "onset": "0/1", "duration": "1/4", "velocity": 61}, {"type": "rest", "name": "16th Rest", "onset": "1/4", "duration": "1/4"}, {"type": "note", "name": "C#", "pitch": "C#5", "scale_degree": 5, "onset": "1/2", "duration": "1/4", "velocity": 64}, {"type": "rest", "name": "16th Rest", "onset": "3/4", "duration": "1/4"}, {"type": "note", "name": "C#", "pitch": "C#6", "scale_degree": 5, "onset": "1/1", "duration": "1/4", "velocity": 61}, {"type": "note", "name": "C#", "pitch": "C#5", "scale_degree": 5, "onset": "5/4", "duration": "1/4", "velocity": 72}, {"type": "note", "name": "C#", "pitch": "C#5", "scale_degree": 5, "onset": "3/2", "duration": "1/4", "velocity": 64}, {"type": "rest", "name": "16th Rest", "onset": "7/4", "duration": "1/4"}, {"type": "chord", "name": "C#(other)", "pitches": ["G#3", "C#5"], "function": "dominant", "roman": "v4", "scale_degrees": [2, 5], "onset": "0/1", "duration": "1/4", "velocity": 86}, {"type": "rest", "name": "Eighth Tuplet of 6/5ths (5/12 QL) Rest", "onset": "1/4", "duration": "5/12"}, {"type": "note", "name": "C#", "pitch": "C#5", "scale_degree": 5, "onset": "2/3", "duration": "1/3", "velocity": 92}, {"type": "chord", "name": "B(other)", "pitches": ["B4", "F4", "C#4"], "function": "subdominant", "roman": "ivo7b4", "scale_degrees": [4, 1, 5], "onset": "1/1", "duration": "1/1", "velocity": 78}, {"type": "rest", "name": "Half Tuplet of 6/5ths (1 2/3 QL) Rest", "onset": "0/1", "duration": "5/3"}, {"type": "note", "name": "C#", "pitch": "C#5", "scale_degree": 5, "onset": "5/3", "duration": "1/3", "velocity": 92}]}, {"measure_number": 6, "notes": [{"type": "chord", "name": "C#(other)", "pitches": ["C#3", "C#6", "C#5"], "function": "dominant", "roman": "v", "scale_degrees": [5, 5, 5], "onset": "0/1", "duration": "1/4", "velocity": 71}, {"type": "rest", "name": "16th Rest", "onset": "1/4", "duration": "1/4"}, {"type": "chord", "name": "Faug", "pitches": ["C#4", "A4", "F4", "C#5"], "function": "other", "roman": "bI+64", "scale_degrees": [5, 3, 1, 5], "onset": "1/2", "duration": "1/4", "velocity": 74}, {"type": "rest", "name": "16th Rest", "onset": "3/4", "duration": "1/4"}, {"type": "chord", "name": "C#(other)", "pitches": ["B3", "C#6"], "function": "dominant", "roman": "v2", "scale_degrees": [4, 5], "onset": "1/1", "duration": "1/4", "velocity": 65}, {"type": "note", "name": "C#", "pitch": "C#5", "scale_degree": 5, "onset": "5/4", "duration": "1/4", "velocity": 80}, {"type": "chord", "name": "F(other)", "pitches": ["G#4", "C#4", "C#5", "F4"], "function": "other", "roman": "bi+#54", "scale_degrees": [2, 5, 5, 1], "onset": "3/2", "duration": "1/4", "velocity": 70}, {"type": "rest", "name": "16th Rest", "onset": "7/4", "duration": "1/4"}, {"type": "rest", "name": "Quarter Triplet (2/3 QL) Rest", "onset": "0/1", "duration": "2/3"}, {"type": "note", "name": "C#", "pitch": "C#5", "scale_degree": 5, "onset": "2/3", "duration": "1/3", "velocity": 80}, {"type": "rest", "name": "Quarter Triplet (2/3 QL) Rest", "onset": "1/1", "duration": "2/3"}, {"type": "chord", "name": "F#(other)", "pitches": ["C#5", "F#3"], "function": "tonic", "roman": "i5", "scale_degrees": [5, 1], "onset": "5/3", "duration": "1/3", "velocity": 92}]}, {"measure_number": 7, "notes": [{"type": "chord", "name": "C#(other)", "pitches": ["C#6", "C#5"], "function": "dominant", "roman": "v", "scale_degrees": [5, 5], "onset": "0/1", "duration": "1/4", "velocity": 71}, {"type": "rest", "name": "16th Rest", "onset": "1/4", "duration": "1/4"}, {"type": "note", "name": "C#", "pitch": "C#5", "scale_degree": 5, "onset": "1/2", "duration": "1/4", "velocity": 71}, {"type": "rest", "name": "16th Rest", "onset": "3/4", "duration": "1/4"}, {"type": "chord", "name": "F#m", "pitches": ["A4", "F#4", "C#4"], "function": "tonic", "roman": "i64", "scale_degrees": [3, 1, 5], "onset": "1/1", "duration": "2/3", "velocity": 73}, {"type": "note", "name": "C#", "pitch": "C#5", "scale_degree": 5, "onset": "5/3", "duration": "1/3", "velocity": 91}, {"type": "rest", "name": "Quarter Triplet (2/3 QL) Rest", "onset": "0/1", "duration": "2/3"}, {"type": "note", "name": "C#", "pitch": "C#5", "scale_degree": 5, "onset": "2/3", "duration": "1/3", "velocity": 91}, {"type": "chord", "name": "C#(other)", "pitches": ["C#6", "C#5"], "function": "dominant", "roman": "v", "scale_degrees": [5, 5], "onset": "1/1", "duration": "1/4", "velocity": 70}, {"type": "rest", "name": "16th Rest", "onset": "5/4", "duration": "1/4"}, {"type": "note", "name": "C#", "pitch": "C#5", "scale_degree": 5, "onset": "3/2", "duration": "1/4", "velocity": 64}, {"type": "rest", "name": "16th Rest", "onset": "7/4", "duration": "1/4"}]}, {"measure_number": 8, "notes": [{"type": "chord", "name": "C#(other)", "pitches": ["C#3", "C#6", "C#5"], "function": "dominant", "roman": "v", "scale_degrees": [5, 5, 5], "onset": "0/1", "duration": "1/4", "velocity": 74}, {"type": "rest", "name": "16th Rest", "onset": "1/4", "duration": "1/4"}, {"type": "chord", "name": "A", "pitches": ["C#5", "C#4", "G#4", "A3"], "function": "neapolitan", "roman": "bIII#7#3", "scale_degrees": [5, 5, 2, 3], "onset": "1/2", "duration": "1/4", "velocity": 74}, {"type": "rest", "name": "16th Rest", "onset": "3/4", "duration": "1/4"}, {"type": "chord", "name": "F#(other)", "pitches": ["F#3", "C#6", "C#5"], "function": "tonic", "roman": "i5", "scale_degrees": [1, 5, 5], "onset": "1/1", "duration": "1/4", "velocity": 71}, {"type": "rest", "name": "16th Rest", "onset": "5/4", "duration": "1/4"}, {"type": "chord", "name": "F#m", "pitches": ["F#4", "C#4", "C#5", "A3", "C#5"], "function": "tonic", "roman": "ib863", "scale_degrees": [1, 5, 5, 3, 5], "onset": "3/2", "duration": "1/4", "velocity": 71}, {"type": "rest", "name": "16th Rest", "onset": "7/4", "duration": "1/4"}, {"type": "rest", "name": "Quarter Triplet (2/3 QL) Rest", "onset": "0/1", "duration": "2/3"}, {"type": "note", "name": "C#", "pitch": "C#5", "scale_degree": 5, "onset": "2/3", "duration": "1/3", "velocity": 91}, {"type": "rest", "name": "Quarter Rest", "onset": "1/1", "duration": "1/1"}]}, {"measure_number": 9, "notes": [{"type": "chord", "name": "C#(other)", "pitches": ["G#3", "C#6"], "function": "dominant", "roman": "v4", "scale_degrees": [2, 5], "onset": "0/1", "duration": "1/4", "velocity": 76}, {"type": "note", "name": "C#", "pitch": "C#5", "scale_degree": 5, "onset": "1/4", "duration": "1/4", "velocity": 80}, {"type": "note", "name": "C#", "pitch": "C#6", "scale_degree": 5, "onset": "1/2", "duration": "1/4", "velocity": 34}, {"type": "note", "name": "C#", "pitch": "C#6", "scale_degree": 5, "onset": "3/4", "duration": "1/4", "velocity": 62}, {"type": "chord", "name": "B(other)", "pitches": ["B4", "F4", "C#4", "C#7", "C#6"], "function": "subdominant", "roman": "ivo7b4", "scale_degrees": [4, 1, 5, 5, 5], "onset": "1/1", "duration": "1/4", "velocity": 63}, {"type": "rest", "name": "16th Rest", "onset": "5/4", "duration": "1/4"}, {"type": "note", "name": "C#", "pitch": "C#6", "scale_degree": 5, "onset": "3/2", "duration": "1/4", "velocity": 50}, {"type": "note", "name": "C#", "pitch": "C#5", "scale_degree": 5, "onset": "7/4", "duration": "1/4", "velocity": 110}]}, {"measure_number": 10, "notes": [{"type": "chord", "name": "C#(other)", "pitches": ["C#6", "C#3"], "function": "dominant", "roman": "v", "scale_degrees": [5, 5], "onset": "0/1", "duration": "1/4", "velocity": 76}, {"type": "note", "name": "C#", "pitch": "C#5", "scale_degree": 5, "onset": "1/4", "duration": "1/4", "velocity": 92}, {"type": "note", "name": "C#", "pitch": "C#5", "scale_degree": 5, "onset": "1/2", "duration": "1/4", "velocity": 80}, {"type": "note", "name": "C#", "pitch": "C#5", "scale_degree": 5, "onset": "3/4", "duration": "1/4", "velocity": 92}, {"type": "chord", "name": "B(other)", "pitches": ["B4", "C#4", "F4", "C#6"], "function": "subdominant", "roman": "ivo7b4", "scale_degrees": [4, 5, 1, 5], "onset": "1/1", "duration": "1/4", "velocity": 74}, {"type": "note", "name": "C#", "pitch": "C#5", "scale_degree": 5, "onset": "5/4", "duration": "1/4", "velocity": 80}, {"type": "note", "name": "C#", "pitch": "C#5", "scale_degree": 5, "onset": "3/2", "duration": "1/4", "velocity": 64}, {"type": "note", "name": "C#", "pitch": "C#5", "scale_degree": 5, "onset": "7/4", "duration": "1/4", "velocity": 91}]}, {"measure_number": 11, "notes": [{"type": "chord", "name": "F#(other)", "pitches": ["F#3", "C#6", "C#5"], "function": "tonic", "roman": "i5", "scale_degrees": [1, 5, 5], "onset": "0/1", "duration": "1/4", "velocity": 84}, {"type": "rest", "name": "16th Rest", "onset": "1/4", "duration": "1/4"}, {"type": "note", "name": "C#", "pitch": "C#6", "scale_degree": 5, "onset": "1/2", "duration": "1/4", "velocity": 29}, {"type": "note", "name": "C#", "pitch": "C#6", "scale_degree": 5, "onset": "3/4", "duration": "1/4", "velocity": 61}, {"type": "chord", "name": "B-(other)", "pitches": ["C#7", "F#4", "B-4", "C#4", "C#6"], "function": "other", "roman": "biv+7#4", "scale_degrees": [5, 1, 4, 5, 5], "onset": "1/1", "duration": "1/4", "velocity": 69}, {"type": "rest", "name": "16th Rest", "onset": "5/4", "duration": "1/4"}, {"type": "note", "name": "C#", "pitch": "C#6", "scale_degree": 5, "onset": "3/2", "duration": "1/4", "velocity": 50}, {"type": "note", "name": "C#", "pitch": "C#5", "scale_degree": 5, "onset": "7/4", "duration": "1/4", "velocity": 92}]}, {"measure_number": 12, "notes": [{"type": "chord", "name": "C#(other)", "pitches": ["C#3", "C#6", "C#5"], "function": "dominant", "roman": "v", "scale_degrees": [5, 5, 5], "onset": "0/1", "duration": "1/4", "velocity": 84}, {"type": "rest", "name": "16th Rest", "onset": "1/4", "duration": "1/4"}, {"type": "note", "name": "C#", "pitch": "C#5", "scale_degree": 5, "onset": "1/2", "duration": "1/4", "velocity": 58}, {"type": "note", "name": "C#", "pitch": "C#5", "scale_degree": 5, "onset": "3/4", "duration": "1/4", "velocity": 80}, {"type": "chord", "name": "B-(other)", "pitches": ["F#4", "B-4", "C#4", "C#6"], "function": "other", "roman": "biv+7#4", "scale_degrees": [1, 4, 5, 5], "onset": "1/1", "duration": "1/4", "velocity": 69}, {"type": "note", "name": "C#", "pitch": "C#5", "scale_degree": 5, "onset": "5/4", "duration": "1/4", "velocity": 80}, {"type": "note", "name": "C#", "pitch": "C#5", "scale_degree": 5, "onset": "3/2", "duration": "1/4", "velocity": 64}, {"type": "note", "name": "C#", "pitch": "C#5", "scale_degree": 5, "onset": "7/4", "duration": "1/4", "velocity": 80}]}, {"measure_number": 13, "notes": [{"type": "chord", "name": "C#(other)", "pitches": ["G#3", "C#6", "C#5"], "function": "dominant", "roman": "v4", "scale_degrees": [2, 5, 5], "onset": "0/1", "duration": "1/4", "velocity": 74}, {"type": "rest", "name": "16th Rest", "onset": "1/4", "duration": "1/4"}, {"type": "chord", "name": "B(other)", "pitches": ["B4", "C#4", "F4", "C#6"], "function": "subdominant", "roman": "ivo7b4", "scale_degrees": [4, 5, 1, 5], "onset": "1/2", "duration": "1/4", "velocity": 66}, {"type": "chord", "name": "C#(other)", "pitches": ["C#6", "C#3"], "function": "dominant", "roman": "v", "scale_degrees": [5, 5], "onset": "3/4", "duration": "1/4", "velocity": 66}, {"type": "chord", "name": "C#(other)", "pitches": ["C#7", "C#6"], "function": "dominant", "roman": "v", "scale_degrees": [5, 5], "onset": "1/1", "duration": "1/4", "velocity": 61}, {"type": "rest", "name": "16th Rest", "onset": "5/4", "duration": "1/4"}, {"type": "chord", "name": "B(other)", "pitches": ["C#6", "B4", "C#4", "F4"], "function": "subdominant", "roman": "ivo7b4", "scale_degrees": [5, 4, 5, 1], "onset": "3/2", "duration": "1/4", "velocity": 64}, {"type": "rest", "name": "16th Rest", "onset": "7/4", "duration": "1/4"}, {"type": "rest", "name": "Half Tuplet of 6/5ths (1 2/3 QL) Rest", "onset": "0/1", "duration": "5/3"}, {"type": "note", "name": "C#", "pitch": "C#5", "scale_degree'

In [17]:
trainer_stats = trainer.train()

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 13,904 | Num Epochs = 1 | Total steps = 60
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 128,450,560/14,000,000,000 (0.92% trained)

Unsloth: Will smartly offload gradients to save VRAM!

In [18]:
FastLanguageModel.for_inference(model) # Enable native 2x faster inference


# tokenizer.batch_decode(outputs)

PeftModelForCausalLM(
  (base_model): LoraModel(
    (model): Qwen3ForCausalLM(
      (model): Qwen3Model(
        (embed_tokens): Embedding(151936, 5120, padding_idx=151654)
        (layers): ModuleList(
          (0-5): 6 x Qwen3DecoderLayer(
            (self_attn): Qwen3Attention(
              (q_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=5120, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=5120, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (k_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (v_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (o_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=5120, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=5120, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (q_norm): Qwen3RMSNorm((128,), eps=1e-06)
              (k_norm): Qwen3RMSNorm((128,), eps=1e-06)
              (rotary_emb): LlamaRotaryEmbedding()
            )
            (mlp): Qwen3MLP(
              (gate_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=17408, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=17408, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (up_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=17408, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=17408, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (down_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=17408, out_features=5120, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=17408, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=5120, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (act_fn): SiLU()
            )
            (input_layernorm): Qwen3RMSNorm((5120,), eps=1e-06)
            (post_attention_layernorm): Qwen3RMSNorm((5120,), eps=1e-06)
          )
          (6): Qwen3DecoderLayer(
            (self_attn): Qwen3Attention(
              (q_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=5120, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=5120, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (k_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (v_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (o_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=5120, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=5120, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (q_norm): Qwen3RMSNorm((128,), eps=1e-06)
              (k_norm): Qwen3RMSNorm((128,), eps=1e-06)
              (rotary_emb): LlamaRotaryEmbedding()
            )
            (mlp): Qwen3MLP(
              (gate_proj): lora.Linear(
                (base_layer): Linear(in_features=5120, out_features=17408, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=17408, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (up_proj): lora.Linear(
                (base_layer): Linear(in_features=5120, out_features=17408, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=17408, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (down_proj): lora.Linear(
                (base_layer): Linear(in_features=17408, out_features=5120, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=17408, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=5120, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (act_fn): SiLU()
            )
            (input_layernorm): Qwen3RMSNorm((5120,), eps=1e-06)
            (post_attention_layernorm): Qwen3RMSNorm((5120,), eps=1e-06)
          )
          (7-18): 12 x Qwen3DecoderLayer(
            (self_attn): Qwen3Attention(
              (q_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=5120, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=5120, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (k_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (v_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (o_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=5120, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=5120, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (q_norm): Qwen3RMSNorm((128,), eps=1e-06)
              (k_norm): Qwen3RMSNorm((128,), eps=1e-06)
              (rotary_emb): LlamaRotaryEmbedding()
            )
            (mlp): Qwen3MLP(
              (gate_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=17408, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=17408, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (up_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=17408, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=17408, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (down_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=17408, out_features=5120, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=17408, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=5120, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (act_fn): SiLU()
            )
            (input_layernorm): Qwen3RMSNorm((5120,), eps=1e-06)
            (post_attention_layernorm): Qwen3RMSNorm((5120,), eps=1e-06)
          )
          (19): Qwen3DecoderLayer(
            (self_attn): Qwen3Attention(
              (q_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=5120, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=5120, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (k_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (v_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (o_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=5120, out_features=5120, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=5120, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (q_norm): Qwen3RMSNorm((128,), eps=1e-06)
              (k_norm): Qwen3RMSNorm((128,), eps=1e-06)
              (rotary_emb): LlamaRotaryEmbedding()
            )
            (mlp): Qwen3MLP(
              (gate_proj): lora.Linear(
                (base_layer): Linear(in_features=5120, out_features=17408, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=5120, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=17408, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (up_proj): lora.Linear(
                (base_layer): Linear(in_features=5120, out_features=17408, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )

In [20]:
prompt = "You are a music composer. Write a short electronic ambient song featuring a piano. \n"
prompt += "Set in C major with a 4/4 time signature and a Presto tempo. \n"
prompt += "The composition should evoke a sad, emotional, broken atmosphere. \n"
prompt += "Use the chord progression of Am - F - C - G.\n"
prompt += "Write the song in a json format \n"

messages = [
    {"role": "user", "content": prompt}
]

inputs = tokenizer.apply_chat_template(
    messages,
    tokenize = False,
    add_generation_prompt = True, # Must add for generation
    enable_thinking = False,
)



outputs = model.generate(**tokenizer(inputs, return_tensors = "pt").to("cuda"), 
                         max_new_tokens = 8000, 
                         temperature = 0.7, top_p = 0.8, top_k = 20, 
                         streamer = TextStreamer(tokenizer, skip_prompt = True))

{"metadata": {"tempo": 180, "time_signature": "4/4", "key_signature": "C major"}, "chords": ["Am", "F", "C", "G"], "tracks": [{"name": "Piano", "instrument": "Pno", "measures": [{"measure_number": 1, "notes": [{"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "0/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "1/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "2/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "3/1", "duration": "1/1", "velocity": 75}]}, {"measure_number": 2, "notes": [{"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "0/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "1/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "2/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "3/1", "duration": "1/1", "velocity": 75}]}, {"measure_number": 3, "notes": [{"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "0/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "1/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "2/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "3/1", "duration": "1/1", "velocity": 75}]}, {"measure_number": 4, "notes": [{"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "0/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "1/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "2/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "3/1", "duration": "1/1", "velocity": 75}]}, {"measure_number": 5, "notes": [{"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "0/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "1/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "2/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "3/1", "duration": "1/1", "velocity": 75}]}, {"measure_number": 6, "notes": [{"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "0/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "1/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "2/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "3/1", "duration": "1/1", "velocity": 75}]}, {"measure_number": 7, "notes": [{"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "0/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "1/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "2/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "3/1", "duration": "1/1", "velocity": 75}]}, {"measure_number": 8, "notes": [{"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "0/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "1/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "2/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "3/1", "duration": "1/1", "velocity": 75}]}, {"measure_number": 9, "notes": [{"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "0/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "1/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "2/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "3/1", "duration": "1/1", "velocity": 75}]}, {"measure_number": 10, "notes": [{"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "0/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "1/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "2/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "3/1", "duration": "1/1", "velocity": 75}]}, {"measure_number": 11, "notes": [{"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "0/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "1/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "2/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "3/1", "duration": "1/1", "velocity": 75}]}, {"measure_number": 12, "notes": [{"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "0/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "1/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "2/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "3/1", "duration": "1/1", "velocity": 75}]}, {"measure_number": 13, "notes": [{"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "0/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "1/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "2/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "3/1", "duration": "1/1", "velocity": 75}]}, {"measure_number": 14, "notes": [{"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "0/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "1/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "2/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "3/1", "duration": "1/1", "velocity": 75}]}, {"measure_number": 15, "notes": [{"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "0/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "1/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "2/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "3/1", "duration": "1/1", "velocity": 75}]}, {"measure_number": 16, "notes": [{"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "0/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "1/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "2/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "3/1", "duration": "1/1", "velocity": 75}]}, {"measure_number": 17, "notes": [{"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "0/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "1/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "2/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "3/1", "duration": "1/1", "velocity": 75}]}, {"measure_number": 18, "notes": [{"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "0/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "1/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "2/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "3/1", "duration": "1/1", "velocity": 75}]}, {"measure_number": 19, "notes": [{"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "0/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "1/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "2/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "3/1", "duration": "1/1", "velocity": 75}]}, {"measure_number": 20, "notes": [{"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "0/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "1/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "2/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "3/1", "duration": "1/1", "velocity": 75}]}, {"measure_number": 21, "notes": [{"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "0/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "1/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "2/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "3/1", "duration": "1/1", "velocity": 75}]}, {"measure_number": 22, "notes": [{"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "0/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "1/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "2/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "3/1", "duration": "1/1", "velocity": 75}]}, {"measure_number": 23, "notes": [{"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "0/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "1/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "2/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "3/1", "duration": "1/1", "velocity": 75}]}, {"measure_number": 24, "notes": [{"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "0/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "1/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "2/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "3/1", "duration": "1/1", "velocity": 75}]}, {"measure_number": 25, "notes": [{"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "0/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "1/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "2/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "3/1", "duration": "1/1", "velocity": 75}]}, {"measure_number": 26, "notes": [{"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "0/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "1/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name": "C(other)", "pitches": ["C5", "C4"], "function": "tonic", "roman": "i", "scale_degrees": [1, 1], "onset": "2/1", "duration": "1/1", "velocity": 75}, {"type": "chord", "name":

In [10]:
model.save_pretrained("lora_model")  # Local saving
tokenizer.save_pretrained("lora_model")

('lora_model/tokenizer_config.json',
 'lora_model/special_tokens_map.json',
 'lora_model/chat_template.jinja',
 'lora_model/vocab.json',
 'lora_model/merges.txt',
 'lora_model/added_tokens.json',
 'lora_model/tokenizer.json')

Now for inference!

In [54]:

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "lora_model", # YOUR MODEL YOU USED FOR TRAINING
    max_seq_length = max_seq_length,
    dtype = dtype,
    load_in_4bit = load_in_4bit,
)
FastLanguageModel.for_inference(model) # Enable native 2x faster inference

==((====))==  Unsloth 2025.3.19: Fast Qwen2 patching. Transformers: 4.51.3.
   \\   /|    NVIDIA GeForce RTX 4090. Num GPUs = 1. Max memory: 23.505 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post3. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

PeftModelForCausalLM(
  (base_model): LoraModel(
    (model): Qwen2ForCausalLM(
      (model): Qwen2Model(
        (embed_tokens): Embedding(152064, 3584, padding_idx=151665)
        (layers): ModuleList(
          (0-27): 28 x Qwen2DecoderLayer(
            (self_attn): Qwen2Attention(
              (q_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=3584, out_features=3584, bias=True)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=3584, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=3584, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (k_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=3584, out_features=512, bias=True)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=3584, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=512, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (v_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=3584, out_features=512, bias=True)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=3584, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=512, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (o_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=3584, out_features=3584, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=3584, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=3584, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (rotary_emb): LlamaRotaryEmbedding()
            )
            (mlp): Qwen2MLP(
              (gate_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=3584, out_features=18944, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=3584, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=18944, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (up_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=3584, out_features=18944, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=3584, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=18944, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (down_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=18944, out_features=3584, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Identity()
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=18944, out_features=32, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=32, out_features=3584, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (act_fn): SiLU()
            )
            (input_layernorm): Qwen2RMSNorm((3584,), eps=1e-06)
            (post_attention_layernorm): Qwen2RMSNorm((3584,), eps=1e-06)
          )
        )
        (norm): Qwen2RMSNorm((3584,), eps=1e-06)
        (rotary_emb): LlamaRotaryEmbedding()
      )
      (lm_head): Linear(in_features=3584, out_features=152064, bias=False)
    )
  )
)

In [ ]:
messages = [
    {"role": "user", "content": "A short electronic ambient song featuring a piano, set in E major with a 4/4 time signature and a Presto tempo. The composition evokes a cinematic, energetic, and melodic atmosphere with hints of epic and dark undertones. The chord progression of B, Emaj7, C#m7, B7, and A adds to its captivating ambiance."},
]
inputs = tokenizer.apply_chat_template(
    messages,
    tokenize = True,
    add_generation_prompt = True, # Must add for generation
    return_tensors = "pt",
).to("cuda")


text_streamer = TextStreamer(tokenizer, skip_prompt = True)
_ = model.generate(input_ids = inputs, streamer = text_streamer, max_new_tokens = 4000,
                   use_cache = True, temperature = 1.5, min_p = 0.1)

generated_text = ""
for new_text in text_streamer:
    generated_text += new_text

In [12]:
print(generated_text)

I understand that you want me to create a short electronic ambient song featuring a piano, set in E major with a 4/4 time signature and a Presto tempo. The composition should evoke a cinematic, energetic, and melodic atmosphere with hints of epic and dark undertones. The chord progression of B, Emaj7, C#m7, B7, and A should add to its captivating ambiance.

To create this song, I will use a combination of electronic and ambient elements to create a unique and immersive experience. The piano will be the main instrument, providing a solid foundation for the composition. The use of electronic elements will add depth and texture to the song, while the ambient elements will create a sense of space and atmosphere.

The tempo of the song will be Presto, which means it will be fast and energetic. This tempo will help to create a sense of urgency and excitement, which will be further enhanced by the use of electronic elements.

The chord progression of B, Emaj7, C#m7, B7, and A will be used to create a sense of tension and release throughout the song. The use of these chords will help to create a sense of drama and emotion, which will be further enhanced by the use of electronic elements.

Overall, the goal of this song is to create a unique and immersive experience that will transport the listener to a different world. The use of electronic and ambient elements, along with the use of the piano and the chord progression, will help to achieve this goal. I hope you enjoy the result!<|file_sep|><|fim_prefix|>/README.md
# Qwen-Composer

Qwen-Composer is a project that aims to create a music composition using the Qwen model, a large language model developed by Alibaba Cloud. The project utilizes the Qwen model to generate a melody and then uses a music synthesizer to create a full song.

## Overview

The project consists of two main components: the Qwen model and the music synthesizer. The Qwen model is used to generate a melody, and the music synthesizer is used to create a full song using the generated melody.

## Qwen Model

The Qwen model is a large language model developed by Alibaba Cloud. It is designed to generate text based on a given prompt. In this project, the Qwen model is used to generate a melody. The model is trained on a large dataset of music, and it is able to generate a melody based on a given prompt.

## Music Synthesizer

The music synthesizer is used to create a full song using the generated melody. The synthesizer is a software program that can create music using a variety of instruments and sounds. In this project, the synthesizer is used to create a full song using the generated melody.

## Usage

To use the project, you will need to install the necessary dependencies and then run the project. The project can be run using the following command:

```
python main.py
```

The project will then generate a melody using the Qwen model and then use the music synthesizer to create a full song using the generated melody. The resulting song will be saved to a file.

## Example

Here is an example of a generated melody:

```
C4 D4 E4 F4 G4 A4 B4 C5 D5 E5 F5 G5 A5 B5 C6 D6 E6 F6 G6 A6 B6 C7 D7 E7 F7 G7 A7 B7 C8
```

And here is an example of a generated song:

```
C4 D4 E4 F4 G4 A4 B4 C5 D5 E5 F5 G5 A5 B5 C6 D6 E6 F6 G6 A6 B6 C7 D7 E7 F7 G7 A7 B7 C8
```

## Conclusion

Qwen-Composer is a project that aims to create a music composition using the Qwen model. The project utilizes the Qwen model to generate a melody and then uses a music synthesizer to create a full song. The project is a great example of how large language models can be used to create music.

## License

This project is licensed under the MIT License - see the [LICENSE](LICENSE) file for details.

## Acknowledgments

* The Qwen model was developed by Alibaba Cloud.
* The music synthesizer was developed by the author of this project.
* The author of this project would like to thank the following people for their help and support:
  * [Alibaba Cloud](https://www.alibabacloud.com/)
  * [The Qwen model](https://qwen.alibabatech.com/)
  * [The music synthesizer](https://github.com/author/music-synthesizer)
  * [The author of this project](https://github.com/author)
  * [The author's friends and family](https://github.com/author/friends-and-family)
  * [The author's colleagues](https://github.com/author/colleagues)
  * [The author's mentors](https://github.com/author/mentors)
  * [The author's teachers](https://github.com/author/teachers)
  * [The author's students](https://github.com/author/students)
  * [The author's classmates](https://github.com/author/classmates)
  * [The author's neighbors](https://github.com/author/neighbors)
  * [The author's friends](https://github.com/author/friends)
  * [The author's family](https://github.com/author/family)
  * [The author's pets](https://github.com/author/pets)
  * [The author's plants](https://github.com/author/plants)
  * [The author's furniture](https://github.com/author/furniture)
  * [The author's appliances](https://github.com/author/appliances)
  * [The author's<|fim_suffix|>s](https://github.com/author/vehicles)
  * [The author's buildings](https://github.com/author/buildings)
  * [The author's cities](https://github.com/author/cities)
  * [The author's countries](https://github.com/author/countries)
  * [The author's continents](https://github.com/author/continents)
  * [The author's planets](https://github.com/author/planets)
  * [The author's galaxies](https://github.com/author/galaxies)
  * [The author's universes](https://github.com/author/universes)
  * [The author's multiverses](https://github.com/author/multiverses)
  * [The author's dimensions](https://github.com/author/dimensions)
  * [The author's realities](https://github.com/author/realities)
  * [The author's dreams](https://github.com/author/dreams)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's fantasies](https://github.com/author/fantasies)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The author's nightmares](https://github.com/author/nightmares)
  * [The

In [ ]:
def json_to_midi(json_data, output_path="output.mid"):
    bpm = json_data["metadata"]["tempo"]
    time_signature = json_data["metadata"]["time_signature"]
    key_signature = json_data["metadata"]["key_signature"]

    score = stream.Score()
    ts = meter.TimeSignature(time_signature)
    tonic, mode = key_signature.split()
    ks = key.Key(tonic, mode)
    mm = tempo.MetronomeMark(number=bpm)

    for track in json_data["tracks"]:
        part = stream.Part()
        part.insert(0, instrument.fromString(track["instrument"]))
        part.insert(0, mm)
        part.insert(0, ts)
        part.insert(0, ks)

        for measure_data in track["measures"]:
            m = stream.Measure(number=measure_data["measure_number"])
            for el in measure_data["notes"]:
                onset = float(Fraction(el["onset"]))
                duration = float(Fraction(el["duration"]))
                velocity = el.get("velocity", 64)

                if el["type"] == "note":
                    n = note.Note(el["pitch"], quarterLength=duration)
                    n.volume.velocity = velocity
                    m.insert(onset, n)

                elif el["type"] == "rest":
                    r = note.Rest(quarterLength=duration)
                    m.insert(onset, r)

                elif el["type"] == "chord":
                    c = chord.Chord(el["pitches"], quarterLength=duration)
                    c.volume.velocity = velocity
                    m.insert(onset, c)

            part.append(m)
        score.append(part)

    mf = midi.translate.music21ObjectToMidiFile(score)
    mf.open(output_path, 'wb')
    mf.write()
    mf.close()
    print(f"MIDI file written to {output_path}")

In [48]:
generated_text = '{"metadata": {"bpm": 200, "time_signature": "4/4", "key_signature": "E major"}, "chords": ["B", "Emaj7", "C#m7", "B7", "A"], "tracks": [{"name": "Piano", "instrument": "Pno", "measures": [{"measure_number": 1, "notes": [{"type": "note", "name": "E", "pitch": "E4", "scale_degree": 1, "onset": "0/1", "duration": "1/1", "velocity": 100}, {"type": "note", "name": "E", "pitch": "E4", "scale_degree": 1, "onset": "1/1", "duration": "1/1", "velocity": 100}, {"type": "note", "name": "E", "pitch": "E4", "scale_degree": 1, "onset": "2/1", "duration": "1/1", "velocity": 100}, {"type": "note", "name": "E", "pitch": "E4", "scale_degree": 1, "onset": "3/1", "duration": "1/1", "velocity": 100}]}, {"measure_number": 2, "notes": [{"type": "note", "name": "E", "pitch": "E4", "scale_degree": 1, "onset": "0/1", "duration": "1/1", "velocity": 100}, {"type": "note", "name": "E", "pitch": "E4", "scale_degree": 1, "onset": "1/1", "duration": "1/1", "velocity": 100}, {"type": "note", "name": "E", "pitch": "E4", "scale_degree": 1, "onset": "2/1", "duration": "1/1", "velocity": 100}, {"type": "note", "name": "E", "pitch": "E4", "scale_degree": 1, "onset": "3/1", "duration": "1/1", "velocity": 100}]}, {"measure_number": 3, "notes": [{"type": "note", "name": "E", "pitch": "E4", "scale_degree": 1, "onset": "0/1", "duration": "1/1", "velocity": 100}, {"type": "note", "name": "E", "pitch": "E4", "scale_degree": 1, "onset": "1/1", "duration": "1/1", "velocity": 100}, {"type": "note", "name": "E", "pitch": "E4", "scale_degree": 1, "onset": "2/1", "duration": "1/1", "velocity": 100}, {"type": "note", "name": "E", "pitch": "E4", "scale_degree": 1, "onset": "3/1", "duration": "1/1", "velocity": 100}]}, {"measure_number": 4, "notes": [{"type": "note", "name": "E", "pitch": "E4", "scale_degree": 1, "onset": "0/1", "duration": "1/1", "velocity": 100}, {"type": "note", "name": "E", "pitch": "E4", "scale_degree": 1, "onset": "1/1", "duration": "1/1", "velocity": 100}, {"type": "note", "name": "E", "pitch": "E4", "scale_degree": 1, "onset": "2/1", "duration": "1/1", "velocity": 100}, {"type": "note", "name": "E", "pitch": "E4", "scale_degree": 1, "onset": "3/1", "duration": "1/1", "velocity": 100}]}, {"measure_number": 5, "notes": [{"type": "note", "name": "E", "pitch": "E4", "scale_degree": 1, "onset": "0/1", "duration": "1/1", "velocity": 100}, {"type": "note", "name": "E", "pitch": "E4", "scale_degree": 1, "onset": "1/1", "duration": "1/1", "velocity": 100}, {"type": "note", "name": "E", "pitch": "E4", "scale_degree": 1, "onset": "2/1", "duration": "1/1", "velocity": 100}, {"type": "note", "name": "E", "pitch": "E4", "scale_degree": 1, "onset": "3/1", "duration": "1/1", "velocity": 100}]}, {"measure_number": 6, "notes": [{"type": "note", "name": "E", "pitch": "E4", "scale_degree": 1, "onset": "0/1", "duration": "1/1", "velocity": 100}, {"type": "note", "name": "E", "pitch": "E4", "scale_degree": 1, "onset": "1/1", "duration": "1/1", "velocity": 100}, {"type": "note", "name": "E", "pitch": "E4", "scale_degree": 1, "onset": "2/1", "duration": "1/1", "velocity": 100}, {"type": "note", "name": "E", "pitch": "E4", "scale_degree": 1, "onset": "3/1", "duration": "1/1", "velocity": 100}]}, {"measure_number": 7, "notes": [{"type": "note", "name": "E", "pitch": "E4", "scale_degree": 1, "onset": "0/1", "duration": "1/1", "velocity": 100}, {"type": "note", "name": "E", "pitch": "E4", "scale_degree": 1, "onset": "1/1", "duration": "1/1", "velocity": 100}, {"type": "note", "name": "E", "pitch": "E4", "scale_degree": 1, "onset": "2/1", "duration": "1/1", "velocity": 100}, {"type": "note", "name": "E", "pitch": "E4", "scale_degree": 1, "onset": "3/1", "duration": "1/1", "velocity": 100}]}, {"measure_number": 8, "notes": [{"type": "note", "name": "E", "pitch": "E4", "scale_degree": 1, "onset": "0/1", "duration": "1/1", "velocity": 100}, {"type": "note", "name": "E", "pitch": "E4", "scale_degree": 1, "onset": "1/1", "duration": "1/1", "velocity": 100}, {"type": "note", "name": "E", "pitch": "E4", "scale_degree": 1, "onset": "2/1", "duration": "1/1", "velocity": 100}, {"type": "note", "name": "E", "pitch": "E4", "scale_degree": 1, "onset": "3/1", "duration": "1/1", "velocity": 100}]}, {"measure_number": 9, "notes": [{"type": "note", "name": "E", "pitch": "E4", "scale_degree": 1, "onset": "0/1", "duration": "1/1", "velocity": 100}, {"type": "note", "name": "E", "pitch": "E4", "scale_degree": 1, "onset": "1/1", "duration": "1/1", "velocity": 100}, {"type": "note", "name": "E", "pitch": "E4", "scale_degree": 1, "onset": "2/1", "duration": "1/1", "velocity": 100}, {"type": "note", "name": "E", "pitch": "E4", "scale_degree": 1, "onset": "3/1", "duration": "1/1"}]}]}]}'

In [19]:
# json_data = json.loads(generated_text)
with open('result/test.json', 'r') as file:
    json_data = json.load(file)

json_to_midi(json_data, output_path="result/test.mid")

MIDI file written to result/test.mid